export const priorityCmsRoutes = [
  "home",
  "driving-license",
  "pricing",
  "traffic-laws",
  "contact-us",
  "appointment",
  "helps",
  "who-are-we",
  "where-are-we",
  "monitor-privacy-policy",
  "student-privacy-policy",
  "manage-my-cookies",
  "legal-notice",
  "privacy-policy",
  "general-terms-and-conditions",
  "request-for-school-partnership",
  "b2b-partnership-request",
  "becoming-an-independent-instructor",
  "driving-instructor-salary",
  "monitor-faqs",
  "frequently-asked-questions",
  "highway-code-glossary",
  "driving-licence-glossary",
  "person-with-a-disability",
  "terms-and-conditions",
  "privacy-and-cookies",
  "refund-policy",
  "disclaimer",
];

export const priorityCmsRouteSet = new Set(priorityCmsRoutes);
