const field = (key, label, type = "text") => ({ key, label, type });
const button = (key, label) => field(key, label, "button");

const supportFields = [
  field("title", "Page heading"),
  field("intro", "Introduction", "textarea"),
  field("body", "Policy / page content", "longtext"),
];
const guideFields = [
  field("heroTitle", "Hero title"),
  field("heroDescription", "Hero description", "textarea"),
  field("sectionTitle", "Main section title"),
  field("sectionDescription", "Main section description", "textarea"),
  field("ctaTitle", "CTA title"),
  field("ctaText", "CTA description", "textarea"),
  button("ctaButton", "CTA button"),
];
const standardFields = [
  field("heroTitle", "Hero title"),
  field("heroDescription", "Hero description", "textarea"),
  button("heroButton", "Hero button"),
  field("sectionTitle", "Main section title"),
  field("sectionDescription", "Main section description", "textarea"),
  field("ctaTitle", "CTA title"),
  button("ctaButton", "CTA button"),
];

const supportSlugs = [
  "monitor-privacy-policy",
  "student-privacy-policy",
  "manage-my-cookies",
  "legal-notice",
  "privacy-policy",
  "general-terms-and-conditions",
  "terms-and-conditions",
  "privacy-and-cookies",
  "refund-policy",
  "disclaimer",
];
const guideSlugs = [];

export const sitePageSchemas = Object.fromEntries([
  [
    "home",
    {
      label: "Home page content",
      fields: [
        field("heroTitle", "Hero title"),
        field("heroDescription", "Hero description", "textarea"),
        button("heroButton", "Hero button"),
        field("offer1Title", "First offer title"),
        field("offer2Title", "Second offer title"),
        field("servicesLabel", "Services label"),
        field("servicesTitle", "Services heading"),
        button("serviceLearnMore", "Service card button"),
        button("servicesButton", "All services button"),
        field("locationLabel", "Location label"),
        field("locationTitle", "Location heading"),
        field("locationDescription", "Location description", "textarea"),
        field("faqLabel", "FAQ label"),
        field("faqTitle", "FAQ heading"),
        field("paymentLabel", "Payment label"),
        field("paymentTitle", "Payment heading"),
      ],
    },
  ],
  ...["student-login", "teacher-login"].map((slug) => [
    slug,
    {
      label: slug === "student-login" ? "Student login page" : "Teacher login page",
      fields: [
        field("logoImage", "Login logo", "image"), field("logoAlt", "Logo alt text"),
        field("loginTitle", "Login title"), field("usernameLabel", "Username label"), field("usernamePlaceholder", "Username placeholder"),
        field("passwordLabel", "Password label"), field("passwordPlaceholder", "Password placeholder"),
        button("forgotButton", "Forgot password link"), button("loginButton", "Login button"), field("loggingText", "Logging text"),
        field("accountPrompt", "No account prompt"), button("registerButton", "Registration link"),
        field("pageBackground", "Page background", "color"), field("panelBackground", "Panel background", "color"),
      ],
    },
  ]),
  ...supportSlugs.map((slug) => [
    slug,
    { label: "Policy content", fields: supportFields },
  ]),
  ...guideSlugs.map((slug) => [
    slug,
    { label: "Guide content", fields: guideFields },
  ]),
  [
    "monitor-faqs",
    {
      label: "Monitor FAQs page",
      fields: [
        field("heroEyebrow", "Hero eyebrow"), field("heroTitle", "Hero title"), field("heroDescription", "Hero description", "textarea"),
        field("heroImage", "Hero image", "image"), field("heroImageAlt", "Hero image alt text"), field("heroBackground", "Hero background", "color"),
        field("highlights", "Hero highlights - one per line", "longtext"), field("homeLabel", "Breadcrumb home label"),
        field("sectionEyebrow", "FAQ section eyebrow"), field("sectionTitle", "FAQ section title"), field("sectionDescription", "FAQ section description", "textarea"),
        field("groupBadgeColor", "Group number badge color", "color"), field("groupTitleColor", "Group title color", "color"),
        field("faqCardBackground", "FAQ card background", "color"), field("faqHoverBackground", "FAQ hover background", "color"),
        field("guidesTitle", "Guide navigation title"), field("guide1Label", "Guide link 1 label"), field("guide2Label", "Guide link 2 label"),
        field("guide3Label", "Guide link 3 label"), field("guide4Label", "Guide link 4 label"), field("guide5Label", "Guide link 5 label"),
        field("ctaTitle", "Help CTA title"), field("ctaText", "Help CTA text", "textarea"), button("ctaButton", "Help CTA button"),
      ],
    },
  ],
  [
    "helps",
    {
      label: "Help centre page",
      fields: [
        field("heroTitle", "Hero title"), field("heroDescription", "Hero description", "textarea"),
        field("heroImage", "Hero image", "image"), field("heroImageAlt", "Hero image alt text"), field("heroBackground", "Hero background", "color"),
        field("searchLabel", "Search accessibility label"), field("searchPlaceholder", "Search placeholder"),
        field("sectionTitle", "Resources section title"), field("sectionDescription", "Resources section description", "textarea"),
        field("resourcesBackground", "Resources section background", "color"), field("resourceCardBackground", "Resource card background", "color"),
        ...Array.from({ length: 3 }, (_, index) => [
          field(`resource${index + 1}Image`, `Resource ${index + 1} image`, "image"), field(`resource${index + 1}ImageAlt`, `Resource ${index + 1} image alt text`),
          field(`resource${index + 1}Title`, `Resource ${index + 1} title`), field(`resource${index + 1}Text`, `Resource ${index + 1} description`, "textarea"),
          button(`resource${index + 1}Button`, `Resource ${index + 1} button`),
        ]).flat(),
        field("ctaTitle", "Support CTA title"), field("ctaText", "Support CTA description", "textarea"),
        field("ctaLeftImage", "Support left image", "image"), field("ctaLeftImageAlt", "Support left image alt text"),
        field("ctaRightImage", "Support right image", "image"), field("ctaRightImageAlt", "Support right image alt text"),
        field("ctaBackground", "Support CTA background", "color"), button("ctaButton", "Support CTA button"),
      ],
    },
  ],
  [
    "highway-code-glossary",
    {
      label: "Highway Code glossary page",
      fields: [
        field("heroEyebrow", "Hero eyebrow"), field("heroTitle", "Hero title"), field("heroDescription", "Hero description", "textarea"),
        field("heroImage", "Hero image", "image"), field("heroImageAlt", "Hero image alt text"), field("heroBackground", "Hero background", "color"),
        field("highlights", "Hero highlights - one per line", "longtext"), field("homeLabel", "Breadcrumb home label"),
        field("sectionEyebrow", "Glossary section eyebrow"), field("sectionTitle", "Glossary section title"), field("sectionDescription", "Glossary description", "textarea"),
        field("alphabet", "Alphabet characters"), field("activeLetterColor", "Active alphabet color", "color"), field("termCardBackground", "Term card background", "color"),
        ...Array.from({ length: 10 }, (_, index) => [field(`term${index + 1}Title`, `Term ${index + 1}`), field(`term${index + 1}Definition`, `Term ${index + 1} definition`, "textarea")]).flat(),
        field("guidesTitle", "Guide navigation title"), field("guide1Label", "Guide link 1 label"), field("guide2Label", "Guide link 2 label"),
        field("guide3Label", "Guide link 3 label"), field("guide4Label", "Guide link 4 label"), field("guide5Label", "Guide link 5 label"),
        field("ctaTitle", "Help CTA title"), field("ctaText", "Help CTA text", "textarea"), button("ctaButton", "Help CTA button"),
      ],
    },
  ],
  [
    "driving-licence-glossary",
    {
      label: "Driving Licence glossary page",
      fields: [
        field("heroEyebrow", "Hero eyebrow"), field("heroTitle", "Hero title"), field("heroDescription", "Hero description", "textarea"),
        field("heroImage", "Hero image", "image"), field("heroImageAlt", "Hero image alt text"), field("heroBackground", "Hero background", "color"),
        field("highlights", "Hero highlights - one per line", "longtext"), field("homeLabel", "Breadcrumb home label"),
        field("sectionEyebrow", "Glossary section eyebrow"), field("sectionTitle", "Glossary section title"), field("sectionDescription", "Glossary description", "textarea"),
        field("termListBackground", "Term list background", "color"), field("numberBadgeColor", "Number badge color", "color"),
        ...Array.from({ length: 10 }, (_, index) => [field(`term${index + 1}Title`, `Term ${index + 1}`), field(`term${index + 1}Definition`, `Term ${index + 1} definition`, "textarea")]).flat(),
        field("noticeTitle", "Notice title"), field("noticeText", "Notice text", "textarea"), field("noticeBackground", "Notice background", "color"),
        field("guidesTitle", "Guide navigation title"), field("guide1Label", "Guide link 1 label"), field("guide2Label", "Guide link 2 label"),
        field("guide3Label", "Guide link 3 label"), field("guide4Label", "Guide link 4 label"), field("guide5Label", "Guide link 5 label"),
        field("ctaTitle", "Help CTA title"), field("ctaText", "Help CTA text", "textarea"), button("ctaButton", "Help CTA button"),
      ],
    },
  ],
  [
    "person-with-a-disability",
    {
      label: "Disability support page",
      fields: [
        field("heroEyebrow", "Hero eyebrow"), field("heroTitle", "Hero title"), field("heroDescription", "Hero description", "textarea"),
        field("heroImage", "Hero image", "image"), field("heroImageAlt", "Hero image alt text"), field("heroBackground", "Hero background", "color"),
        field("highlights", "Hero highlights - one per line", "longtext"), field("homeLabel", "Breadcrumb home label"),
        field("sectionEyebrow", "Support section eyebrow"), field("sectionTitle", "Support section title"), field("sectionDescription", "Support section description", "textarea"),
        field("stepCardBackground", "Step card background", "color"), field("stepIconColor", "Step icon color", "color"),
        field("step1Title", "Step 1 title"), field("step1Text", "Step 1 description", "textarea"),
        field("step2Title", "Step 2 title"), field("step2Text", "Step 2 description", "textarea"),
        field("step3Title", "Step 3 title"), field("step3Text", "Step 3 description", "textarea"),
        field("step4Title", "Step 4 title"), field("step4Text", "Step 4 description", "textarea"),
        field("contactEyebrow", "Contact CTA eyebrow"), field("contactTitle", "Contact CTA title"), field("contactText", "Contact CTA description", "textarea"),
        field("contactBackground", "Contact CTA background", "color"), button("contactButton", "Contact CTA button"),
        field("guidesTitle", "Guide navigation title"), field("guide1Label", "Guide link 1 label"), field("guide2Label", "Guide link 2 label"),
        field("guide3Label", "Guide link 3 label"), field("guide4Label", "Guide link 4 label"), field("guide5Label", "Guide link 5 label"),
        field("ctaTitle", "Help CTA title"), field("ctaText", "Help CTA text", "textarea"), button("ctaButton", "Help CTA button"),
      ],
    },
  ],
  [
    "frequently-asked-questions",
    {
      label: "Frequently Asked Questions page",
      fields: [
        field("heroTitle", "Hero title"), field("heroDescription", "Hero description", "textarea"),
        field("heroImage", "Hero image", "image"), field("heroImageAlt", "Hero image alt text"), field("heroBackground", "Hero background", "color"),
        field("sectionBackground", "FAQ section background", "color"), field("faqCardBackground", "FAQ card background", "color"),
        field("faqInactiveBackground", "Closed FAQ background", "color"), field("faqActiveBackground", "Open FAQ background", "color"),
        field("ctaTitle", "Support card title"), field("ctaText", "Support card description", "textarea"),
        field("ctaImage", "Support card image", "image"), field("ctaImageAlt", "Support image alt text"),
        field("ctaCardBackground", "Support card background", "color"), field("ctaCardBorderColor", "Support card border", "color"),
        field("contactPhone", "Support phone number"), button("ctaButton", "Support contact button"),
      ],
    },
  ],
  [
    "b2b-partnership-request",
    {
      label: "B2B partnership request page",
      fields: [
        field("heroTitle", "Hero title"), field("heroDescription", "Hero description", "textarea"),
        field("heroImage", "Hero image", "image"), field("heroImageAlt", "Hero image alt text"),
        field("heroBackground", "Hero background", "color"), button("heroButton", "Hero button"),
        field("sectionTitle", "Company section title"), field("sectionDescription", "Company section description", "textarea"),
        field("benefitsImage", "Benefits image", "image"), field("benefitsImageAlt", "Benefits image alt text"),
        field("benefitsTitle", "Benefits card title"), field("benefitsCardBackground", "Benefits card background", "color"),
        field("benefit1", "Benefit 1"), field("benefit2", "Benefit 2"), field("benefit3", "Benefit 3"),
        field("benefit4", "Benefit 4"), field("benefit5", "Benefit 5"),
        field("formTitle", "Form title"), field("formDescription", "Form description", "textarea"),
        field("organizationTitle", "Organization heading"), field("nameLabel", "Name label"), field("namePlaceholder", "Name placeholder"),
        field("companyTypeLabel", "Company type label"), field("companyTypePlaceholder", "Company type placeholder"),
        field("companyTypeOptions", "Company type options - one per line", "longtext"),
        field("phoneLabel", "Phone label"), field("phonePlaceholder", "Phone placeholder"),
        field("emailLabel", "Email label"), field("emailPlaceholder", "Email placeholder"),
        field("cityLabel", "City label"), field("cityPlaceholder", "City placeholder"),
        field("addressLabel", "Address label"), field("addressPlaceholder", "Address placeholder"),
        field("expectationLabel", "Expectation label"), field("expectationHelp", "Expectation help text"), field("messagePlaceholder", "Message placeholder"),
        field("beneficiariesLabel", "Beneficiaries label"), field("beneficiariesPlaceholder", "Beneficiaries placeholder"),
        field("beneficiariesOptions", "Beneficiary options - one per line", "longtext"),
        field("referralLabel", "Referral source label"), field("referralPlaceholder", "Referral source placeholder"),
        field("referralOptions", "Referral source options - one per line", "longtext"), button("submitButton", "Submit button"),
        field("ratingsBackground", "Ratings section background", "color"),
        field("rating1Title", "Rating 1 title"), field("rating1Image", "Rating 1 image", "image"),
        field("rating2Title", "Rating 2 title"), field("rating2Image", "Rating 2 image", "image"),
        field("rating3Title", "Rating 3 title"), field("rating3Image", "Rating 3 image", "image"),
        field("ratingScore", "Rating score text"), field("ratingAriaLabel", "Rating accessibility label"),
      ],
    },
  ],
  [
    "request-for-school-partnership",
    {
      label: "School partnership request page",
      fields: [
        field("heroTitle", "Hero title"), field("heroDescription", "Hero description", "textarea"),
        field("heroImage", "Hero image", "image"), field("heroImageAlt", "Hero image alt text"), field("heroBackground", "Hero background", "color"), button("heroButton", "Hero button"),
        field("sectionTitle", "Benefits section title"), field("sectionDescription", "Benefits description", "textarea"),
        field("personImage", "Benefits person image", "image"), field("personImageAlt", "Person image alt text"), field("carImage", "Benefits car image", "image"), field("carImageAlt", "Car image alt text"),
        field("benefitsTitle", "Benefits card title"), field("benefitsCardBackground", "Benefits card background", "color"),
        field("benefit1", "Benefit 1"), field("benefit2", "Benefit 2"), field("benefit3", "Benefit 3"), field("benefit4", "Benefit 4"), field("benefit5", "Benefit 5"),
        field("formTitle", "Form title"), field("formDescription", "Form description", "textarea"), field("schoolInfoTitle", "School information heading"),
        field("schoolNameLabel", "School name label"), field("schoolNamePlaceholder", "School name placeholder"),
        field("schoolTypeLabel", "School type label"), field("schoolTypePlaceholder", "School type placeholder"), field("schoolTypeOptions", "School types - one per line", "longtext"),
        field("phoneLabel", "Phone label"), field("phonePlaceholder", "Phone placeholder"), field("emailLabel", "Email label"), field("emailPlaceholder", "Email placeholder"),
        field("cityLabel", "City label"), field("cityPlaceholder", "City placeholder"), field("addressLabel", "Address label"), field("addressPlaceholder", "Address placeholder"),
        field("studentCountLabel", "Student count label"), field("studentCountPlaceholder", "Student count placeholder"), field("studentCountOptions", "Student count options - one per line", "longtext"),
        field("associationTypeLabel", "Association type label"), field("associationTypePlaceholder", "Association placeholder"), field("associationTypeOptions", "Association options - one per line", "longtext"),
        field("campusQuestion", "Campus question"), field("yesLabel", "Yes label"), field("noLabel", "No label"), button("submitButton", "Submit button"),
        field("reviewSectionTitle", "Review section title"), field("videoUrl", "YouTube embed URL"), field("videoTitle", "Video accessibility title"),
        field("partnersTitle", "Partner recommendation title"), field("ratingImage", "Rating image", "image"), field("ratingImageAlt", "Rating image alt text"),
        field("ratingTitle", "Rating title"), field("ratingScore", "Rating score"), field("ratingAriaLabel", "Rating accessibility label"),
        field("finalCtaTitle", "Final CTA title"), field("finalCtaBackground", "Final CTA background", "color"), button("finalCtaButton", "Final CTA button"),
      ],
    },
  ],
  [
    "where-are-we",
    {
      label: "Where are we page",
      fields: [
        field("heroEyebrow", "Hero eyebrow"), field("heroTitle", "Hero title"),
        field("heroDescription", "Hero description", "textarea"), field("heroImage", "Hero image", "image"),
        field("heroImageAlt", "Hero image alt text"), field("heroBackground", "Hero background", "color"),
        field("highlights", "Hero highlights — one per line", "longtext"),
        field("sectionTitle", "Location section title"), field("sectionDescription", "Location description", "textarea"),
        field("locationImage", "Location/map image", "image"), field("locationImageAlt", "Location image alt text"),
        field("locationName", "Location name"), field("locationStreet", "Location street"),
        field("addressLabel", "Address label"), field("addressValue", "Address value"),
        field("hoursLabel", "Opening hours label"), field("hoursValue", "Opening hours value"),
        field("phoneLabel", "Phone label"), field("phoneValue", "Phone value"),
        field("journeyEyebrow", "Journey eyebrow"), field("journeyTitle", "Journey title"),
        field("transport1Title", "Transport card 1 title"), field("transport1Text", "Transport card 1 text", "textarea"),
        field("transport2Title", "Transport card 2 title"), field("transport2Text", "Transport card 2 text", "textarea"),
        button("appointmentButton", "Appointment button"),
        field("ctaTitle", "Help CTA title"), field("ctaText", "Help CTA description", "textarea"), button("ctaButton", "Help CTA button"),
      ],
    },
  ],
  [
    "driving-instructor-salary",
    {
      label: "Driving instructor salary page",
      fields: [
        field("heroTitle", "Hero title"),
        field("heroDescription", "Hero description", "textarea"),
        field("heroImage", "Hero image", "image"),
        field("heroImageAlt", "Hero image alt text"),
        field("heroBackground", "Hero background color", "color"),
        button("heroButton", "Hero button"),
        field("statisticsBackground", "Statistics section background", "color"),
        field("statCardBackground", "Statistic card background", "color"),
        field("stat1", "Statistic 1 text"),
        field("stat1Image", "Statistic 1 image", "image"),
        field("stat2", "Statistic 2 text"),
        field("stat2Image", "Statistic 2 image", "image"),
        field("stat3", "Statistic 3 text"),
        field("stat3Image", "Statistic 3 image", "image"),
        field("stat4", "Statistic 4 text"),
        field("stat4Image", "Statistic 4 image", "image"),
        field("sectionTitle", "Simulator section title"),
        field("sectionDescription", "Simulator description", "textarea"),
        field("simulatorBackground", "Simulator background color", "color"),
        field("simulatorCircleColor", "Simulator circle color", "color"),
        field("simulatorCarColor", "Simulator car color", "color"),
        button("ctaButton", "Simulator button"),
      ],
    },
  ],
  [
    "becoming-an-independent-instructor",
    {
      label: "Become an independent instructor page",
      fields: [
        field("heroTitle", "Hero title"), field("heroDescription", "Hero description", "textarea"),
        field("heroImage", "Hero image", "image"), field("heroImageAlt", "Hero image alt text"),
        field("heroBackground", "Hero background color", "color"), button("heroButton", "Hero button"),
        field("sectionTitle", "Benefits section title"), field("sectionDescription", "Benefits section description", "textarea"),
        field("benefitsBackground", "Benefits section background", "color"), field("benefitCardBackground", "Benefit card background", "color"),
        field("benefit1Title", "Benefit group 1 title"), field("benefit1Items", "Benefit group 1 items — one per line", "longtext"),
        field("benefit2Title", "Benefit group 2 title"), field("benefit2Items", "Benefit group 2 items — one per line", "longtext"),
        field("benefit3Title", "Benefit group 3 title"), field("benefit3Items", "Benefit group 3 items — one per line", "longtext"),
        field("ctaTitle", "Join CTA title"), field("ctaBackground", "Join CTA background", "color"), button("ctaButton", "Join CTA button"),
        field("statCardBackground", "Statistic card background", "color"),
        field("stat1", "Statistic 1 text"), field("stat1Image", "Statistic 1 image", "image"),
        field("stat2", "Statistic 2 text"), field("stat2Image", "Statistic 2 image", "image"),
        field("stat3", "Statistic 3 text"), field("stat3Image", "Statistic 3 image", "image"),
        field("stat4", "Statistic 4 text"), field("stat4Image", "Statistic 4 image", "image"),
        field("simulatorTitle", "Simulator title"), field("simulatorDescription", "Simulator description", "textarea"),
        field("simulatorBackground", "Simulator background", "color"), field("simulatorCircleColor", "Simulator circle color", "color"),
        field("simulatorCarColor", "Simulator car color", "color"), button("simulatorButton", "Simulator button"),
      ],
    },
  ],
  [
    "appointment",
    {
      label: "Appointment page",
      fields: [
        field("heroTitle", "Hero title"),
        field("heroDescription", "Hero description", "textarea"),
        field("heroImage", "Hero image", "image"), field("heroImageAlt", "Hero image alt text"), field("heroBackground", "Hero background", "color"),
        button("heroButton", "Hero booking button"),
        field("bookingTitle", "Booking form title"),
        field("bookingSchool", "Booking school label"), field("bookingHeading", "Booking heading"), field("bookingIntro", "Booking introduction", "textarea"),
        field("courseLabel", "Course label"), field("dateLabel", "Date label"), field("timeLabel", "Time label"), field("durationLabel", "Duration label"),
        field("duration30", "30 minute option"), field("duration60", "1 hour option"), field("duration120", "2 hour option"),
        field("nameLabel", "Name label"), field("emailLabel", "Email label"), field("phoneLabel", "Phone label"), field("notesLabel", "Notes label"),
        field("notesPlaceholder", "Notes placeholder"), field("submitLabel", "Submit button label"), field("submittingLabel", "Submitting label"),
        field("selectedTimeLabel", "Selected time label"), field("chooseTimeText", "Choose time instruction"),
        field("bookingSectionBackground", "Booking section background", "color"), field("bookingPanelBackground", "Booking panel background", "color"),
        field("whyTitle", "Benefits section title"),
        field("benefit1", "Benefit 1"),
        field("benefit1Image", "Benefit 1 image", "image"), field("benefit1ImageAlt", "Benefit 1 image alt text"),
        field("benefit2", "Benefit 2"),
        field("benefit2Image", "Benefit 2 image", "image"), field("benefit2ImageAlt", "Benefit 2 image alt text"),
        field("benefit3", "Benefit 3"),
        field("benefit3Image", "Benefit 3 image", "image"), field("benefit3ImageAlt", "Benefit 3 image alt text"),
        field("benefit4", "Benefit 4"),
        field("benefit4Image", "Benefit 4 image", "image"), field("benefit4ImageAlt", "Benefit 4 image alt text"),
        field("benefitCardBackground", "Benefit card background", "color"),
        field("finalTitle", "Final CTA title"),
        field("finalBackground", "Final CTA background", "color"),
        button("finalButton", "Final CTA button"),
      ],
    },
  ],
  [
    "pricing",
    {
      label: "Pricing page",
      fields: [
        field("heroTitle", "Hero title"),
        field("heroDescription", "Hero description", "textarea"),
        button("heroButton", "Hero button"),
        field("packagesTitle", "Packages section title"),
        field("trainingTitle", "Training CTA title"),
        button("trainingButton", "Training CTA button"),
        field("cpfTitle", "CPF rates title"),
        field("licenceOffersTitle", "Driving licence offers title"),
        field("supervisedTitle", "Supervised driving title"),
        field("carteTitle", "À la carte title"),
        field("carteDescription", "À la carte description", "textarea"),
      ],
    },
  ],
  [
    "who-are-we",
    {
      label: "Who we are page",
      fields: [
        field("heroTitle", "Hero title"),
        field("heroSubtitle", "Hero subtitle", "textarea"),
        field("heroDescription", "Hero description", "textarea"),
        field("heroImage", "Hero image", "image"),
        field("heroImageAlt", "Hero image alt text"),
        button("heroButton", "Hero button"),
        field("sectionTitle", "Mission title"),
        field("sectionDescription", "Mission description", "textarea"),
        field("missionBackground", "Mission card background color", "color"),
        field("mentorTitle", "Mentor section title"),
        field("mentorDescription", "Mentor description", "textarea"),
        field("mentorImage", "Mentor image", "image"),
        field("mentorImageAlt", "Mentor image alt text"),
        field("mentorBackground", "Mentor card background color", "color"),
        field("programsTitle", "Programs title"),
        field("programsIntro", "Programs introduction", "textarea"),
        field("programs", "Programs — one per line", "longtext"),
        field("programsBackground", "Programs card background color", "color"),
        field("reasonsTitle", "Why choose us title"),
        field("reason1", "Reason 1"),
        field("reason1Image", "Reason 1 image", "image"),
        field("reason2", "Reason 2"),
        field("reason2Image", "Reason 2 image", "image"),
        field("reason3", "Reason 3"),
        field("reason3Image", "Reason 3 image", "image"),
        field("reason4", "Reason 4"),
        field("reason4Image", "Reason 4 image", "image"),
        field("contactTitle", "Contact CTA title"),
        field("contactAddress", "Contact address"),
        field("contactPhone", "Contact phone"),
        field("contactEmail", "Contact email"),
        field("contactBackground", "Contact section background color", "color"),
        button("contactButton", "Contact CTA button"),
        field("facebookUrl", "Facebook URL"),
        field("instagramUrl", "Instagram URL"),
        field("tiktokUrl", "TikTok URL"),
        field("youtubeUrl", "YouTube URL"),
      ],
    },
  ],
  [
    "driving-license",
    {
      label: "Driving license page",
      fields: [
        field("heroTitle", "Hero title"),
        button("heroButton", "Hero button"),
        field("packagesTitle", "Packages section title"),
        field("trainingTitle", "First training CTA title"),
        button("trainingButton", "First training CTA button"),
        field("cpfTitle", "CPF section title"),
        field("cpfDescription", "CPF description", "textarea"),
        button("cpfButton", "CPF button"),
        field("accompaniedTitle", "Accompanied section title"),
        field("accompaniedCardTitle", "Accompanied package name"),
        field("accompaniedCardSubtitle", "Accompanied package subtitle"),
        field("accompaniedPrice", "Accompanied sale price"),
        field("accompaniedOldPrice", "Accompanied old price"),
        button("accompaniedButton", "Accompanied signup button"),
        field("accompaniedContentsTitle", "Accompanied contents heading"),
        field(
          "accompaniedFeatures",
          "Accompanied features — one per line",
          "longtext",
        ),
        field("secondTrainingTitle", "Second training CTA title"),
        button("secondTrainingButton", "Second training CTA button"),
        field("carteTitle", "À la carte title"),
        field("carteDescription", "À la carte description", "textarea"),
        field("codePacksTitle", "Highway Code packs title"),
        field("codePacksDescription", "Highway Code packs description"),
        field("certificationTitle", "Certification title"),
        field(
          "certificationDescription",
          "Certification description",
          "textarea",
        ),
        field("servicesLabel", "Services label"),
        field("servicesTitle", "Services section title"),
        field("service1Title", "Service 1 title"),
        field("service1Price", "Service 1 price text"),
        field("service2Title", "Service 2 title"),
        field("service2Price", "Service 2 price text"),
        field("service3Title", "Service 3 title"),
        field("service3Price", "Service 3 price text"),
        button("serviceLearnMore", "Service card button"),
        button("servicesButton", "Services View All button"),
        field("rating1Title", "Rating card 1 title"),
        field("rating2Title", "Rating card 2 title"),
        field("rating3Title", "Rating card 3 title"),
        field("ratingScore", "Rating score text"),
      ],
    },
  ],
  ...[
    "traffic-laws",
    "contact-us",
  ].map((slug) => [
    slug,
    {
      label: `${slug
        .split("-")
        .map((word) => word[0].toUpperCase() + word.slice(1))
        .join(" ")} content`,
      fields: standardFields,
    },
  ]),
]);

export const getSitePageSchema = (slug) =>
  sitePageSchemas[slug] || { label: "Page content", fields: standardFields };
