"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useSelector } from "react-redux";
import { io } from "socket.io-client";
import { BsEmojiSmile } from "react-icons/bs";
import { FaMicrophone, FaMicrophoneSlash, FaPaperPlane, FaPhone, FaPhoneSlash, FaPlus, FaSearch, FaVideo, FaVideoSlash } from "react-icons/fa";
import { HiOutlineDotsHorizontal } from "react-icons/hi";
import { IoMdAttach } from "react-icons/io";
import { getChatContacts, getChatMessages } from "@/features/API";

const ui = { font: { h1: "text-base md:text-lg font-semibold tracking-tight" }, card: "bg-white rounded-xl shadow-sm border border-gray-100", hover: "transition duration-200 ease-out hover:shadow-md hover:-translate-y-[1px]" };
const socketUrl = process.env.NEXT_PUBLIC_SOCKET_URL || (process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api").replace(/\/api\/?$/, "");
const idOf = (value) => String(value?._id || value || "");
const timeOf = (date) => date ? new Date(date).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "";

export default function RealtimeChat() {
  const currentUser = useSelector((state) => state.user.user);
  const token = useSelector((state) => state.user.token);
  const myId = idOf(currentUser);
  const [contacts, setContacts] = useState([]), [selectedId, setSelectedId] = useState(""), [messages, setMessages] = useState([]), [draft, setDraft] = useState(""), [search, setSearch] = useState(""), [filter, setFilter] = useState("all"), [onlineIds, setOnlineIds] = useState(new Set()), [typingUser, setTypingUser] = useState(""), [error, setError] = useState(""), [connected, setConnected] = useState(false);
  const [incomingCall, setIncomingCall] = useState(null), [activeCall, setActiveCall] = useState(null), [callStatus, setCallStatus] = useState(""), [muted, setMuted] = useState(false), [cameraOff, setCameraOff] = useState(false), [playbackBlocked, setPlaybackBlocked] = useState(false), [remoteTrackKinds, setRemoteTrackKinds] = useState(new Set());
  const socketRef = useRef(null), peerRef = useRef(null), localStreamRef = useRef(null), remoteStreamRef = useRef(null), localVideoRef = useRef(null), remoteVideoRef = useRef(null), remoteAudioRef = useRef(null), selectedRef = useRef(""), contactsRef = useRef([]), activeCallRef = useRef(null), messagesEndRef = useRef(null), typingTimerRef = useRef(null), pendingIceRef = useRef([]);
  useEffect(() => { selectedRef.current = selectedId; }, [selectedId]);
  useEffect(() => { contactsRef.current = contacts; }, [contacts]);
  useEffect(() => { activeCallRef.current = activeCall; }, [activeCall]);
  useEffect(() => { messagesEndRef.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, typingUser]);

  const loadContacts = useCallback(async () => { try { const response = await getChatContacts(); const list = response.data?.data || []; setContacts(list); setSelectedId((current) => current || idOf(list[0])); socketRef.current?.emit("presence:check", { userIds: list.map(idOf) }, (result) => setOnlineIds(new Set(result?.onlineIds || []))); } catch (err) { setError(err.response?.data?.message || "Unable to load chats."); } }, []);
  useEffect(() => { if (token) loadContacts(); }, [token, loadContacts]);
  useEffect(() => { if (!selectedId) { setMessages([]); return; } getChatMessages(selectedId).then((response) => { setMessages(response.data?.data || []); socketRef.current?.emit("message:read", { from: selectedId }); setContacts((items) => items.map((item) => idOf(item) === selectedId ? { ...item, unreadCount: 0 } : item)); }).catch((err) => setError(err.response?.data?.message || "Unable to load messages.")); }, [selectedId]);

  const closePeer = useCallback(() => { peerRef.current?.close(); peerRef.current = null; pendingIceRef.current = []; localStreamRef.current?.getTracks().forEach((track) => track.stop()); localStreamRef.current = null; remoteStreamRef.current = null; if (localVideoRef.current) localVideoRef.current.srcObject = null; if (remoteVideoRef.current) remoteVideoRef.current.srcObject = null; if (remoteAudioRef.current) remoteAudioRef.current.srcObject = null; setIncomingCall(null); setActiveCall(null); setCallStatus(""); setMuted(false); setCameraOff(false); setPlaybackBlocked(false); setRemoteTrackKinds(new Set()); }, []);
  const ensureMedia = useCallback(async (type) => { const existing = localStreamRef.current; if (existing && (type !== "video" || existing.getVideoTracks().length > 0)) return existing; existing?.getTracks().forEach((track) => track.stop()); const stream = await navigator.mediaDevices.getUserMedia({ audio: { echoCancellation: true, noiseSuppression: true, autoGainControl: true }, video: type === "video" ? { width: { ideal: 1280 }, height: { ideal: 720 }, facingMode: "user" } : false }); localStreamRef.current = stream; if (localVideoRef.current) { localVideoRef.current.srcObject = stream; localVideoRef.current.play().catch(() => {}); } return stream; }, []);
  const playRemoteMedia = useCallback(async () => { const stream = remoteStreamRef.current; if (!stream) return; if (remoteVideoRef.current) remoteVideoRef.current.srcObject = stream; if (remoteAudioRef.current) { remoteAudioRef.current.srcObject = stream; try { await remoteAudioRef.current.play(); setPlaybackBlocked(false); } catch { setPlaybackBlocked(true); } } }, []);
  const ensurePeer = useCallback(async (peerId, type) => { if (peerRef.current) return peerRef.current; const configuration = { iceServers: [{ urls: process.env.NEXT_PUBLIC_STUN_URL || "stun:stun.l.google.com:19302" }], bundlePolicy: "max-bundle", iceCandidatePoolSize: 10 }; if (process.env.NEXT_PUBLIC_TURN_URL) configuration.iceServers.push({ urls: process.env.NEXT_PUBLIC_TURN_URL, username: process.env.NEXT_PUBLIC_TURN_USERNAME, credential: process.env.NEXT_PUBLIC_TURN_CREDENTIAL }); const peer = new RTCPeerConnection(configuration); const stream = await ensureMedia(type); stream.getTracks().forEach((track) => peer.addTransceiver(track, { direction: "sendrecv", streams: [stream] })); const remoteStream = new MediaStream(); remoteStreamRef.current = remoteStream; peer.onicecandidate = (event) => { if (event.candidate) socketRef.current?.emit("webrtc:ice", { to: peerId, candidate: event.candidate }); }; peer.ontrack = (event) => { const track = event.track; if (!remoteStream.getTracks().some((item) => item.id === track.id)) remoteStream.addTrack(track); remoteStreamRef.current = remoteStream; setRemoteTrackKinds((current) => new Set([...current, track.kind])); const attachAndPlay = () => playRemoteMedia(); track.onunmute = attachAndPlay; track.onended = () => setRemoteTrackKinds((current) => { const next = new Set(current); next.delete(track.kind); return next; }); attachAndPlay(); }; peer.onconnectionstatechange = () => { if (peer.connectionState === "connected") { setCallStatus("Connected"); playRemoteMedia(); } if (peer.connectionState === "failed") { setError("Media connection failed. A TURN server may be required for this network."); closePeer(); } if (peer.connectionState === "closed") closePeer(); }; peer.oniceconnectionstatechange = () => { if (["checking", "new"].includes(peer.iceConnectionState)) setCallStatus("Connecting media..."); }; peerRef.current = peer; return peer; }, [closePeer, ensureMedia, playRemoteMedia]);

  useEffect(() => {
    if (!token) return undefined;
    const socket = io(socketUrl, { auth: { token }, withCredentials: true, transports: ["websocket", "polling"] }); socketRef.current = socket;
    socket.on("connect", () => { setConnected(true); setError(""); const ids = contactsRef.current.map(idOf); socket.emit("presence:check", { userIds: ids }, (result) => setOnlineIds(new Set(result?.onlineIds || []))); });
    socket.on("disconnect", () => { setConnected(false); setOnlineIds(new Set()); });
    socket.on("connect_error", (err) => setError(err.message || "Realtime connection failed."));
    socket.on("presence:update", ({ userId, online }) => setOnlineIds((current) => { const next = new Set(current); online ? next.add(String(userId)) : next.delete(String(userId)); return next; }));
    socket.on("message:new", (message) => { const otherId = idOf(message.sender) === myId ? idOf(message.receiver) : idOf(message.sender); if (otherId === selectedRef.current) { setMessages((items) => items.some((item) => idOf(item) === idOf(message)) ? items : [...items, message]); socket.emit("message:read", { from: otherId }); } loadContacts(); });
    socket.on("typing", ({ from, typing }) => { if (String(from) === selectedRef.current) setTypingUser(typing ? String(from) : ""); });
    socket.on("call:invite", ({ from, type, caller }) => setIncomingCall({ from, type, caller }));
    socket.on("call:accept", async ({ from, type }) => { try { setActiveCall({ peerId: from, type }); setCallStatus("Connecting..."); const peer = await ensurePeer(from, type); const offer = await peer.createOffer(); await peer.setLocalDescription(offer); socket.emit("webrtc:offer", { to: from, description: offer, type }); } catch (err) { setError(err.message); closePeer(); } });
    socket.on("call:reject", () => { setError("Call declined."); closePeer(); }); socket.on("call:end", closePeer);
    socket.on("webrtc:offer", async ({ from, description, type }) => { try { const peer = await ensurePeer(from, type); await peer.setRemoteDescription(description); for (const candidate of pendingIceRef.current.splice(0)) await peer.addIceCandidate(candidate); const answer = await peer.createAnswer(); await peer.setLocalDescription(answer); socket.emit("webrtc:answer", { to: from, description: answer }); setCallStatus("Connecting media..."); } catch (err) { setError(err.message); closePeer(); } });
    socket.on("webrtc:answer", async ({ description }) => { const peer = peerRef.current; if (!peer) return; await peer.setRemoteDescription(description); for (const candidate of pendingIceRef.current.splice(0)) await peer.addIceCandidate(candidate); setCallStatus("Connecting media..."); }); socket.on("webrtc:ice", async ({ candidate }) => { if (!candidate) return; try { const peer = peerRef.current; if (peer?.remoteDescription) await peer.addIceCandidate(candidate); else pendingIceRef.current.push(candidate); } catch {} });
    return () => { socket.disconnect(); socketRef.current = null; closePeer(); };
  }, [token, myId, loadContacts, ensurePeer, closePeer]);
  useEffect(() => { if (localVideoRef.current && localStreamRef.current) { localVideoRef.current.srcObject = localStreamRef.current; localVideoRef.current.play().catch(() => {}); } playRemoteMedia(); }, [activeCall, playRemoteMedia]);

  const selected = contacts.find((contact) => idOf(contact) === selectedId);
  const filteredContacts = useMemo(() => contacts.filter((contact) => { const matches = `${contact.name} ${contact.email}`.toLowerCase().includes(search.toLowerCase()); return matches && (filter === "active" ? onlineIds.has(idOf(contact)) : filter === "unread" ? contact.unreadCount > 0 : true); }), [contacts, search, filter, onlineIds]);
  const sendMessage = () => { const body = draft.trim(); if (!body || !selectedId) return; socketRef.current?.emit("message:send", { to: selectedId, body }, (result) => { if (!result?.ok) setError(result?.message || "Message failed."); }); setDraft(""); socketRef.current?.emit("typing", { to: selectedId, typing: false }); };
  const onDraft = (value) => { setDraft(value); if (!selectedId) return; socketRef.current?.emit("typing", { to: selectedId, typing: true }); clearTimeout(typingTimerRef.current); typingTimerRef.current = setTimeout(() => socketRef.current?.emit("typing", { to: selectedId, typing: false }), 1000); };
  const startCall = async (type) => { if (!selectedId) return; if (!socketRef.current?.connected) { setError("Realtime connection is offline. Please wait for reconnection."); return; } try { await ensureMedia(type); setActiveCall({ peerId: selectedId, type }); setCallStatus("Calling..."); socketRef.current.emit("call:invite", { to: selectedId, type }, (result) => { if (!result?.ok) { setError(result.message); closePeer(); } }); } catch (err) { setError(err.name === "NotAllowedError" ? "Microphone/camera permission was denied." : err.message); closePeer(); } };
  const acceptCall = async () => { const call = incomingCall; if (!call) return; try { await ensureMedia(call.type); setIncomingCall(null); setActiveCall({ peerId: call.from, type: call.type }); setCallStatus("Connecting..."); socketRef.current?.emit("call:accept", { to: call.from, type: call.type }, (result) => { if (!result?.ok) { setError(result.message); closePeer(); } }); } catch { setError("Microphone/camera permission was denied."); socketRef.current?.emit("call:reject", { to: call.from }); closePeer(); } };
  const rejectCall = () => { if (incomingCall) socketRef.current?.emit("call:reject", { to: incomingCall.from }); closePeer(); }, endCall = () => { const peerId = activeCallRef.current?.peerId; if (peerId) socketRef.current?.emit("call:end", { to: peerId }); closePeer(); }, toggleMute = () => { const next = !muted; localStreamRef.current?.getAudioTracks().forEach((track) => { track.enabled = !next; }); setMuted(next); }, toggleCamera = () => { const next = !cameraOff; localStreamRef.current?.getVideoTracks().forEach((track) => { track.enabled = !next; }); setCameraOff(next); };

  return <main className="min-h-screen w-full bg-[#F6F7FB] flex flex-col md:flex-row gap-2 md:gap-4 font-sans">
    <aside className={`w-full md:w-[300px] ${ui.card} ${ui.hover} flex flex-col overflow-hidden`}><header className="flex items-center justify-between px-3 py-3 border-b border-gray-100"><h1 className={ui.font.h1}>Chat Box</h1><button onClick={() => document.getElementById("chat-search")?.focus()} className="w-8 h-8 rounded-lg bg-blue-600 text-white flex items-center justify-center hover:bg-blue-700 transition"><FaPlus size={11} /></button></header><div className="px-3 py-2"><div className="flex items-center bg-gray-100 px-2 py-2 rounded-lg focus-within:ring-2 focus-within:ring-blue-500 transition"><FaSearch className="text-gray-400 mr-2 text-xs" /><input id="chat-search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search" className="bg-transparent w-full outline-none text-sm text-gray-700" /></div></div><nav className="px-3"><div className="flex bg-gray-100 rounded-lg p-1 text-xs">{["all", "active", "unread"].map((item) => <button key={item} onClick={() => setFilter(item)} className={`flex-1 rounded-md py-1 capitalize ${filter === item ? "bg-white font-medium shadow-sm" : "text-gray-500"}`}>{item}</button>)}</div></nav><section className="flex-1 overflow-auto px-2 py-2 space-y-1">{filteredContacts.map((contact) => { const contactId = idOf(contact); return <article key={contactId} onClick={() => setSelectedId(contactId)} className={`flex items-center justify-between p-2 rounded-lg cursor-pointer ${selectedId === contactId ? "bg-blue-50" : "hover:bg-gray-50"}`}><div className="flex min-w-0 items-center gap-2"><div className="relative w-9 h-9 shrink-0 rounded-full bg-gray-300 overflow-hidden">{contact.avatar && <img src={contact.avatar} alt="" className="h-full w-full object-cover" />}<span className={`absolute bottom-0 right-0 h-2.5 w-2.5 rounded-full border-2 border-white ${onlineIds.has(contactId) ? "bg-green-500" : "bg-gray-400"}`} /></div><div className="min-w-0"><p className="text-sm font-medium truncate">{contact.name}</p><p className="text-xs text-gray-500 truncate max-w-[120px]">{contact.lastMessage?.body || contact.email}</p></div></div><div className="text-right"><p className="text-[10px] text-gray-400">{timeOf(contact.lastMessage?.createdAt)}</p>{contact.unreadCount > 0 && <span className="inline-block mt-1 text-[10px] bg-blue-600 text-white px-2 py-0.5 rounded-full">{contact.unreadCount}</span>}</div></article>; })}{!filteredContacts.length && <p className="p-4 text-center text-xs text-gray-500">No chats found.</p>}</section></aside>
    <section className={`flex-1 ${ui.card} ${ui.hover} flex flex-col overflow-hidden`}><header className="flex items-center justify-between px-4 md:px-6 py-3 border-b border-gray-100"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-full bg-gray-300 overflow-hidden">{selected?.avatar && <img src={selected.avatar} alt="" className="h-full w-full object-cover" />}</div><div><h2 className="text-base font-semibold tracking-tight">{selected?.name || "Select a conversation"}</h2><p className="text-[11px] text-gray-500">{selected ? (!connected ? "Connecting..." : onlineIds.has(selectedId) ? "Online" : "Offline") : ""}</p></div></div><div className="flex items-center gap-3 text-gray-500"><button disabled={!selected || !connected} onClick={() => startCall("video")} aria-label="Video call"><FaVideo className="hover:text-blue-600 transition" /></button><button disabled={!selected || !connected} onClick={() => startCall("audio")} aria-label="Audio call"><FaPhone className="hover:text-blue-600 transition" /></button><HiOutlineDotsHorizontal /></div></header>{error && <button onClick={() => setError("")} className="bg-red-50 px-4 py-2 text-left text-xs text-red-700">{error}</button>}<div className="flex-1 overflow-auto p-3 md:p-5 space-y-3 bg-[#F8FAFF]">{messages.map((message) => { const mine = idOf(message.sender) === myId; return <div key={idOf(message)} className={`flex flex-col ${mine ? "items-end" : "items-start"}`}><div className={`${mine ? "bg-blue-100" : "bg-white border border-gray-100 shadow-sm"} p-2.5 rounded-xl max-w-[90%] md:max-w-md text-sm whitespace-pre-wrap break-words`}>{message.body}</div><span className="text-[10px] text-gray-400 mt-1">{timeOf(message.createdAt)}</span></div>; })}{typingUser && <p className="text-xs text-gray-400">{selected?.name} is typing...</p>}<div ref={messagesEndRef} /></div><footer className="p-2 md:p-3 border-t border-gray-100 flex items-center gap-2 bg-white"><BsEmojiSmile className="text-gray-500 text-sm" /><IoMdAttach className="text-gray-500 text-sm" /><input value={draft} disabled={!selected || !connected} onChange={(e) => onDraft(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendMessage(); } }} placeholder="Message..." className="flex-1 bg-gray-100 px-3 py-2 rounded-lg outline-none text-sm focus:ring-2 focus:ring-blue-500 disabled:opacity-50" /><button disabled={!draft.trim() || !selected || !connected} onClick={sendMessage} className="bg-blue-600 hover:bg-blue-700 disabled:opacity-50 transition text-white p-2.5 rounded-lg"><FaPaperPlane size={12} /></button></footer></section>
    {incomingCall && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-sm rounded-2xl bg-white p-6 text-center shadow-2xl"><div className="mx-auto h-16 w-16 rounded-full bg-gray-200" /><h3 className="mt-4 text-lg font-semibold">{incomingCall.caller?.name || "Incoming call"}</h3><p className="mt-1 text-sm text-gray-500">Incoming {incomingCall.type} call</p><div className="mt-6 flex justify-center gap-5"><button onClick={rejectCall} className="flex h-12 w-12 items-center justify-center rounded-full bg-red-600 text-white"><FaPhoneSlash /></button><button onClick={acceptCall} className="flex h-12 w-12 items-center justify-center rounded-full bg-green-600 text-white"><FaPhone /></button></div></div></div>}
    {activeCall && <div className="fixed inset-0 z-[100] flex flex-col bg-slate-950"><audio ref={remoteAudioRef} autoPlay playsInline /><div className="relative flex-1 overflow-hidden"><video ref={remoteVideoRef} autoPlay playsInline muted className="h-full w-full object-cover" />{activeCall.type === "video" && callStatus === "Connected" && !remoteTrackKinds.has("video") && <p className="absolute left-1/2 top-1/2 -translate-x-1/2 text-sm text-white/70">Waiting for opponent video...</p>}<video ref={localVideoRef} autoPlay playsInline muted className="absolute bottom-5 right-5 h-36 w-24 rounded-xl bg-slate-800 object-cover shadow-xl md:h-48 md:w-36" /><div className="absolute left-0 top-0 p-5 text-white"><h3 className="font-semibold">{contacts.find((item) => idOf(item) === activeCall.peerId)?.name || "Call"}</h3><p className="text-xs text-white/70">{callStatus}</p></div>{playbackBlocked && <button onClick={playRemoteMedia} className="absolute left-1/2 top-1/2 -translate-x-1/2 rounded-full bg-white px-5 py-3 text-sm font-semibold text-slate-900 shadow-xl">Tap to enable sound</button>}</div><div className="flex justify-center gap-4 bg-slate-900 p-5"><button onClick={toggleMute} className="flex h-12 w-12 items-center justify-center rounded-full bg-white/15 text-white">{muted ? <FaMicrophoneSlash /> : <FaMicrophone />}</button>{activeCall.type === "video" && <button onClick={toggleCamera} className="flex h-12 w-12 items-center justify-center rounded-full bg-white/15 text-white">{cameraOff ? <FaVideoSlash /> : <FaVideo />}</button>}<button onClick={endCall} className="flex h-12 w-12 items-center justify-center rounded-full bg-red-600 text-white"><FaPhoneSlash /></button></div></div>}
  </main>;
}
