"use client";
import Image from "next/image";
import Link from "next/link";
import { FaStar } from "react-icons/fa";
import useCmsPageContent from "@/hooks/useCmsPageContent";
import { CmsRichText, cmsButtonProps } from "@/components/cms/CmsContent";

const controlClass = "h-[45px] w-full rounded-[9px] border border-[#c9d6e9] bg-[#f6f8fb] px-4 !text-[14px] text-[#21262d] outline-none transition focus:border-[#174a9b]";
const lines = (value, fallback) => value ? String(value).replace(/<li[^>]*>/gi, "\n").replace(/<br\s*\/?\s*>/gi, "\n").replace(/<[^>]+>/g, "").split("\n").map((x) => x.trim()).filter(Boolean) : fallback;
function Field({ label, type = "text", placeholder }) { return <label><span className="mb-2 block !text-[13px] font-semibold">{label}</span><input type={type} placeholder={placeholder} className={controlClass} /></label>; }
function SelectField({ label, placeholder, options }) { return <label><span className="mb-2 block !text-[13px] font-semibold">{label}</span><select defaultValue="" className={controlClass}><option value="" disabled>{placeholder}</option>{options.map((x) => <option key={x} value={x}>{x}</option>)}</select></label>; }

export default function RequestForSchoolPartnershipPage() {
  const { content } = useCmsPageContent("request-for-school-partnership");
  const s = content?.settings || {};
  const copy = (key, fallback) => s[key]?.trim?.() || fallback;
  const benefitDefaults = ["Discounts on Driving Licence Packages", "Uncapped Earning Opportunities", "Competitions & Prize Draws", "Campus Tours with Goodies & Entertainment", "Partner program (Connect with partners that support student life)"];
  const benefits = benefitDefaults.map((x, i) => copy(`benefit${i + 1}`, x));
  return <main className="overflow-hidden bg-white text-[#202124]">
    <section style={{ backgroundColor: s.heroBackground || "#eaf0f9" }}><div className="mx-auto grid min-h-[560px] max-w-[1280px] items-center gap-10 px-5 py-14 md:grid-cols-2 lg:px-10"><div className="max-w-[620px]"><h1 className="text-[35px] font-bold leading-[1.18] sm:text-[40px] lg:text-[42px]">{copy("heroTitle", "Grow Your Driving School with PermisGo")}</h1><CmsRichText html={s.heroDescription} fallback="Join our partner-school network and unlock tools, visibility and exclusive benefits to grow your business." className="mt-7 max-w-[640px] !text-[16px] leading-7 text-[#72777d]" /><Link {...cmsButtonProps(s, "heroButton", { href: "#school-partnership-form" })} className="mt-10 inline-flex min-h-[48px] min-w-[300px] items-center justify-center rounded-[9px] bg-[#e4213c] px-8 !text-[15px] font-semibold text-white">{copy("heroButton", "Apply for Partnership")}</Link></div><div className="flex justify-center md:justify-end"><Image src={s.heroImage || "/image/request-hero.png"} alt={copy("heroImageAlt", "Driving school partnership meeting")} width={700} height={560} priority sizes="(max-width: 768px) 92vw, 560px" className="h-auto w-full max-w-[540px] object-contain" /></div></div></section>

    <section className="bg-white px-5 py-20 sm:px-8 lg:py-24"><div className="mx-auto max-w-[1120px]"><h2 className="text-center text-[34px] font-bold lg:text-[38px]">{copy("sectionTitle", "A partnership for your school?")}</h2><CmsRichText html={s.sectionDescription} className="mx-auto mt-4 max-w-3xl text-center !text-[14px] text-[#676c73]" /><div className="relative mt-12 flex min-h-[500px] items-end justify-center sm:px-12 lg:px-[115px]">{s.personImage && <Image src={s.personImage} alt={copy("personImageAlt", "Student")} width={180} height={480} className="absolute bottom-0 left-0 z-10 hidden h-auto w-[115px] object-contain lg:block" />}<div className="flex min-h-[500px] w-full flex-col justify-center rounded-[10px] px-5 py-12 sm:px-12 lg:px-[100px]" style={{ backgroundColor: s.benefitsCardBackground || "#174a9b" }}><h3 className="text-center text-[21px] font-bold text-white">{copy("benefitsTitle", "Exclusive Benefits")}</h3><ul className="mt-8 space-y-5">{benefits.map((x) => <li key={x} className="skew-x-[-11deg] rounded-[8px] bg-[#edf3fb] px-5 py-[14px] text-center"><span className="block skew-x-[11deg] !text-[14px] font-semibold">{x}</span></li>)}</ul></div>{s.carImage && <Image src={s.carImage} alt={copy("carImageAlt", "Driving school car")} width={240} height={180} className="absolute bottom-0 right-0 z-10 hidden h-auto w-[135px] object-contain lg:block" />}</div></div></section>

    <section id="school-partnership-form" className="scroll-mt-24 bg-[#eaf0f9] px-5 py-20 sm:px-8 lg:py-24"><div className="mx-auto max-w-[1060px]"><div className="text-center"><h2 className="text-[34px] font-bold lg:text-[38px]">{copy("formTitle", "Request for School Partnership")}</h2><CmsRichText html={s.formDescription} fallback="Fill out this form with necessary information" className="mt-4 !text-[14px] text-[#676c73]" /></div><form className="mt-12 rounded-[12px] bg-white p-5 shadow-sm sm:p-8 lg:p-[30px]" onSubmit={(e) => e.preventDefault()}><h3 className="text-[20px] font-bold">{copy("schoolInfoTitle", "School Information")}</h3><div className="mt-6 grid gap-x-7 gap-y-5 md:grid-cols-2">
      <Field label={copy("schoolNameLabel", "School Name")} placeholder={copy("schoolNamePlaceholder", "Write name here")} /><SelectField label={copy("schoolTypeLabel", "Type of school")} placeholder={copy("schoolTypePlaceholder", "Select one")} options={lines(s.schoolTypeOptions, ["Driving school", "University", "College", "Other"])} /><Field label={copy("phoneLabel", "Phone Number")} type="tel" placeholder={copy("phonePlaceholder", "Write phone number")} /><Field label={copy("emailLabel", "Email Address")} type="email" placeholder={copy("emailPlaceholder", "Write email address")} /><Field label={copy("cityLabel", "City")} placeholder={copy("cityPlaceholder", "Write city")} /><Field label={copy("addressLabel", "Address")} placeholder={copy("addressPlaceholder", "Write address")} />
      <SelectField label={copy("studentCountLabel", "Number of students")} placeholder={copy("studentCountPlaceholder", "Select one")} options={lines(s.studentCountOptions, ["1-100", "101-500", "501-1000", "More than 1000"])} /><SelectField label={copy("associationTypeLabel", "Type of Association")} placeholder={copy("associationTypePlaceholder", "Select one")} options={lines(s.associationTypeOptions, ["Public", "Private", "Non-profit", "Other"])} />
      <fieldset className="md:col-span-2"><legend className="!text-[13px] font-semibold">{copy("campusQuestion", "Is there another driving school on your campus?")}</legend><div className="mt-3 flex gap-8"><label className="flex items-center gap-2 !text-[13px]"><input type="radio" name="campus-school" className="h-4 w-4 accent-[#174a9b]" />{copy("yesLabel", "Yes")}</label><label className="flex items-center gap-2 !text-[13px]"><input type="radio" name="campus-school" defaultChecked className="h-4 w-4 accent-[#20c45a]" />{copy("noLabel", "No")}</label></div></fieldset>
    </div><button type="submit" className="mt-6 rounded-[8px] px-7 py-3 !text-[15px] font-semibold" style={{ backgroundColor: s.submitButtonColor || "#e4213c", color: s.submitButtonTextColor || "#fff" }}>{copy("submitButton", "Submit")}</button></form></div></section>

    <section className="bg-white px-5 py-20 sm:px-8 lg:py-24"><div className="mx-auto max-w-[1060px]"><h2 className="text-center text-[34px] font-bold lg:text-[38px]">{copy("reviewSectionTitle", "The students' favorite driving school!")}</h2><div className="mt-12 grid items-center gap-8 md:grid-cols-[58%_42%]"><div className="overflow-hidden rounded-[10px] bg-[#eef2f8]"><iframe className="aspect-video w-full" src={copy("videoUrl", "https://www.youtube.com/embed/v3YLlDYHpXg")} title={copy("videoTitle", "PermisGo partner recommendation")} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen /></div><div><h3 className="text-[20px] font-bold text-[#174a9b]">{copy("partnersTitle", "Our partners recommend us!")}</h3><article className="mt-5 rounded-[18px] border-[4px] border-[#e4eaf3] bg-[#f7f9fc] px-6 py-7 text-center">{s.ratingImage && <Image src={s.ratingImage} alt={copy("ratingImageAlt", "Trustpilot")} width={42} height={42} className="mx-auto h-10 w-10 object-contain" />}<h4 className="mt-2 text-[18px] font-bold">{copy("ratingTitle", "Trustpilot Ratings")}</h4><div className="mt-2 flex justify-center gap-3 text-[#ffc52c]" aria-label={copy("ratingAriaLabel", "Five stars")}>{[0,1,2,3,4].map((x) => <FaStar key={x} className="text-[18px]" />)}</div><p className="mt-2 !text-[14px]">{copy("ratingScore", "04 out of 05")}</p></article></div></div><div className="mt-20 rounded-[10px] px-5 py-14 text-center" style={{ backgroundColor: s.finalCtaBackground || "#174a9b" }}><h2 className="text-[24px] font-bold text-white sm:text-[27px]">{copy("finalCtaTitle", "Start Your Driving Journey Today")}</h2><Link {...cmsButtonProps(s, "finalCtaButton", { href: "#school-partnership-form" })} className="mt-8 inline-flex min-h-[48px] min-w-[300px] items-center justify-center rounded-[9px] bg-[#e4213c] px-8 !text-[15px] font-semibold text-white">{copy("finalCtaButton", "Apply for Partnership")}</Link></div></div></section>
  </main>;
}
