"use client";

import dynamic from "next/dynamic";
import { useEffect, useState } from "react";
import { createLearningContent, deleteLearningContent, getAdminLearningContents, permanentlyDeleteLearningContent, updateLearningContent } from "@/features/API";
import { mediaUrl } from "@/utils/mediaUrl";

const EbookEditor = dynamic(() => import("./_components/EbookEditor"), { ssr: false, loading: () => <div className="h-64 animate-pulse rounded-xl bg-slate-100" /> });
const template = `<h2>Introduction</h2><p></p><h2>Rules Explained</h2><p></p><h2>Real-Life Examples</h2><p></p><h2>Illustrations / Diagrams</h2><p></p><h2>Remember Points</h2><ul><li></li></ul><h2>Common Mistakes</h2><p></p><h2>Exam Tips</h2><p></p>`;
const empty = { title: "", category: "", section: "General", subtitle: "", content: "", status: "active", order: 0 };
const PAGE_SIZE = 12;

export default function AdminCodeEbooksPage() {
  const [allItems, setItems] = useState([]); const [page, setPage] = useState(0); const [form, setForm] = useState(empty); const [cover, setCover] = useState(null); const [videos, setVideos] = useState([]); const [materials, setMaterials] = useState([]); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState("");
  const load = () => getAdminLearningContents({ type: "code-ebook" }).then(({ data }) => setItems(data?.data || [])).catch((e) => setNotice(e.response?.data?.message || "Could not load lessons.")).finally(() => setLoading(false));
  useEffect(() => { load(); }, []);
  const reset = () => { setForm(empty); setCover(null); setVideos([]); setMaterials([]); setEditing(null); };
  const addVideo = () => setVideos((list) => [...list, { title: "", url: "", thumbnail: "", durationMinutes: 0 }]);
  const updateVideo = (i, key, value) => setVideos((list) => list.map((video, index) => index === i ? { ...video, [key]: value } : video));
  const submit = async (e) => {
    e.preventDefault();
    if (!form.title.trim() || !form.category.trim() || (!editing && !cover)) return setNotice("Chapter, lesson title and cover image are required.");
    const data = new FormData(); data.append("type", "code-ebook"); Object.entries(form).forEach(([key, value]) => data.append(key, value)); data.append("videos", JSON.stringify(videos.filter((video) => video.title && video.url))); if (cover) data.append("image", cover); materials.forEach((item) => data.append("materials", item.file)); data.append("materialMeta", JSON.stringify(materials.map(({ title, readMinutes }) => ({ title, readMinutes }))));
    setSaving(true); try { editing ? await updateLearningContent(editing, data) : await createLearningContent(data); setNotice(editing ? "Lesson updated." : "Lesson created."); reset(); await load(); } catch (err) { setNotice(err.response?.data?.message || "Could not save lesson."); } finally { setSaving(false); }
  };
  const edit = (item) => { setEditing(item._id); setForm({ title: item.title || "", category: item.category || "", section: item.section || "General", subtitle: item.subtitle || "", content: item.content || "", status: item.status || "active", order: item.order || 0 }); setVideos(item.videos || []); setMaterials([]); setCover(null); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const pages = Math.max(1, Math.ceil(allItems.length / PAGE_SIZE));
  const items = allItems.slice(page * PAGE_SIZE, page * PAGE_SIZE + PAGE_SIZE);
  const remove = async (item) => { if (!confirm(`Permanently delete "${item.title}"? This cannot be undone.`)) return; await permanentlyDeleteLearningContent(item._id); if (editing === item._id) reset(); await load(); setPage((current) => Math.min(current, Math.max(0, Math.ceil((allItems.length - 1) / PAGE_SIZE) - 1))); };

  return <main className="min-h-screen bg-[#f5f7fb] p-4 sm:p-6"><div className="mx-auto max-w-7xl"><h1 className="text-2xl font-bold text-[#173f87]">Code eBook Lessons</h1><p className="mt-1 text-sm text-slate-500">Manage chapters, professional lesson content, videos and downloads.</p>
    <form onSubmit={submit} className="mt-6 rounded-2xl bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Field label="Chapter name *" value={form.category} onChange={(value) => setForm({...form,category:value})} placeholder="Legal provisions regarding road traffic" /><Field label="Section name" value={form.section} onChange={(value) => setForm({...form,section:value})} placeholder="Signs and placards" /><Field label="Lesson title *" value={form.title} onChange={(value) => setForm({...form,title:value})} placeholder="Warning signs: general information" /><Field label="Short subtitle" value={form.subtitle} onChange={(value) => setForm({...form,subtitle:value})} /><label className="text-sm font-bold">Cover image {editing ? "" : "*"}<input type="file" accept="image/*" onChange={(e) => setCover(e.target.files?.[0] || null)} className="mt-2 block w-full text-xs font-normal" /></label></div>
      <div className="mt-5 flex items-center justify-between"><p className="text-sm font-bold">Professional lesson content *</p><button type="button" onClick={() => setForm({...form,content:template})} className="rounded-lg bg-blue-50 px-3 py-2 text-xs font-bold text-[#173f87]">Insert standard structure</button></div><div className="mt-2 min-h-[300px]"><EbookEditor key={editing || "new"} value={form.content} onChange={(content) => setForm((old) => ({...old,content}))} /></div>
      <Section title="Lesson Videos" action={addVideo} actionText="+ Add video">{videos.map((video, i) => <div key={i} className="grid gap-2 rounded-xl bg-slate-50 p-3 md:grid-cols-4"><Field label="Title" value={video.title} onChange={(v) => updateVideo(i,"title",v)} /><Field label="Video URL" value={video.url} onChange={(v) => updateVideo(i,"url",v)} /><Field label="Thumbnail URL" value={video.thumbnail} onChange={(v) => updateVideo(i,"thumbnail",v)} /><Field type="number" label="Minutes" value={video.durationMinutes} onChange={(v) => updateVideo(i,"durationMinutes",v)} /><button type="button" onClick={() => setVideos((list) => list.filter((_, index) => index !== i))} className="w-fit text-xs font-bold text-red-600">Remove</button></div>)}</Section>
      <Section title="Training Materials / Downloads" action={() => setMaterials((list) => [...list, { title: "", readMinutes: 0, file: null }])} actionText="+ Add material">{materials.map((material, i) => <div key={i} className="grid gap-2 rounded-xl bg-slate-50 p-3 md:grid-cols-3"><Field label="Material title" value={material.title} onChange={(v) => setMaterials((list) => list.map((item,index) => index === i ? {...item,title:v} : item))} /><Field type="number" label="Read minutes" value={material.readMinutes} onChange={(v) => setMaterials((list) => list.map((item,index) => index === i ? {...item,readMinutes:v} : item))} /><label className="text-xs font-bold">File<input type="file" onChange={(e) => setMaterials((list) => list.map((item,index) => index === i ? {...item,file:e.target.files?.[0] || null} : item))} className="mt-2 block w-full font-normal" /></label></div>)}</Section>
      <div className="mt-5 flex flex-wrap items-center gap-3"><select value={form.status} onChange={(e) => setForm({...form,status:e.target.value})} className="rounded-lg border px-3 py-2"><option value="active">Published</option><option value="draft">Draft</option><option value="inactive">Inactive</option></select><input type="number" value={form.order} onChange={(e) => setForm({...form,order:e.target.value})} className="w-24 rounded-lg border px-3 py-2" /><button disabled={saving} className="rounded-lg bg-[#173f87] px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving ? "Saving..." : editing ? "Update Lesson" : "Create Lesson"}</button>{editing && <button type="button" onClick={reset} className="rounded-lg bg-slate-100 px-5 py-2.5 text-sm font-bold">Cancel</button>}{notice && <span className="text-sm font-semibold text-slate-600">{notice}</span>}</div>
    </form>
    <section className="mt-6 rounded-2xl bg-[#e8eef7] p-4">{loading ? <p>Loading...</p> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items.map((item) => <article key={item._id} className="rounded-xl bg-white p-4"><img src={mediaUrl(item.image)} alt={item.title} className="h-28 w-full rounded-lg object-cover" /><p className="mt-3 text-xs font-bold text-[#173f87]">{item.category || "Uncategorized"}</p><h2 className="mt-1 break-words font-bold">{item.title}</h2><p className="mt-1 text-xs text-slate-500">{item.status} · {item.videos?.length || 0} videos · {item.materials?.length || 0} files</p><div className="mt-3 flex gap-2"><button onClick={() => edit(item)} className="rounded bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700">Edit</button><button onClick={() => confirm("Deactivate this lesson?") && deleteLearningContent(item._id).then(load)} className="rounded bg-red-50 px-3 py-1.5 text-xs font-bold text-red-700">Deactivate</button></div></article>)}</div>}</section>
    {editing && <div className="mt-4 flex justify-end"><button type="button" onClick={() => remove(allItems.find((item) => item._id === editing))} className="rounded-lg bg-red-600 px-5 py-2.5 text-sm font-bold text-white">Delete current lesson permanently</button></div>}
    <div className="mt-4 flex flex-col items-center justify-between gap-3 rounded-xl bg-white px-4 py-3 sm:flex-row"><p className="text-xs font-semibold text-slate-500">Page {page + 1} of {pages} · {allItems.length} lessons</p><div className="flex gap-2"><button type="button" disabled={page === 0} onClick={() => setPage((value) => value - 1)} className="rounded-lg border px-4 py-2 text-xs font-bold disabled:opacity-40">Previous</button><button type="button" disabled={page + 1 >= pages} onClick={() => setPage((value) => value + 1)} className="rounded-lg bg-[#173f87] px-4 py-2 text-xs font-bold text-white disabled:opacity-40">Next</button></div></div>
  </div></main>;
}

function Field({ label, value, onChange, type="text", placeholder="" }) { return <label className="text-xs font-bold">{label}<input type={type} value={value} placeholder={placeholder} onChange={(e) => onChange(e.target.value)} className="mt-2 w-full rounded-lg border px-3 py-2.5 font-normal" /></label>; }
function Section({ title, action, actionText, children }) { return <section className="mt-5 rounded-xl border p-4"><div className="flex items-center justify-between"><h2 className="font-bold text-[#173f87]">{title}</h2><button type="button" onClick={action} className="rounded-lg bg-[#e8eef7] px-3 py-2 text-xs font-bold text-[#173f87]">{actionText}</button></div><div className="mt-3 space-y-3">{children}</div></section>; }
