export const BOOKLET_GROUPS = [
  {
    code: "C1",
    title: "MASTERING",
    text: "vehicle handling in light or no traffic",
    skills: [
      "Know the main components and controls of the vehicle, perform interior and exterior checks.",
      "Enter, get into the driver's seat and get out.",
      "Hold, turn the steering wheel and maintain the trajectory.",
      "Start and stop.",
      "Control acceleration and braking at various speeds.",
      "Use the gearbox.",
      "Steer forward in a straight line and around a curve by adapting speed and trajectory.",
      "Look around and warn others.",
      "Perform a reverse manoeuvre and a U-turn safely.",
    ],
  },
  {
    code: "C2",
    title: "To understand",
    text: "the road and drive under normal conditions",
    skills: [
      "Look for signs and useful clues and take them into account.",
      "Position the vehicle on the road and choose the traffic lane.",
      "Adapt your pace to the situation.",
      "Turn right and left in built-up areas.",
      "Detect, identify and cross intersections according to the priority system.",
      "Navigate roundabouts and traffic circles.",
      "Stop and park at an angle, perpendicularly and parallel.",
    ],
  },
  {
    code: "C3",
    title: "Driving",
    text: "in difficult conditions and sharing the road with other users",
    skills: [
      "Assess and maintain safety distances.",
      "Cross, overtake and be overtaken.",
      "Negotiate turns and drive on slopes.",
      "Know the characteristics of other users and behave with respect and courtesy.",
      "Merge, move through and exit a highway.",
      "Drive in a line of vehicles and in heavy traffic.",
      "Drive in difficult weather and at night.",
      "Look around and warn others.",
      "Perform emergency manoeuvres safely.",
    ],
  },
  {
    code: "C4",
    title: "Practice",
    text: "autonomous, safe and economical driving",
    skills: [
      "Follow a route independently.",
      "Prepare and make a safe journey.",
      "Know the main risk factors while driving.",
      "Understand vehicle maintenance and safety checks.",
      "Drive economically and reduce environmental impact.",
      "Apply safe driving behaviour in unfamiliar areas.",
      "Share the road responsibly with vulnerable users.",
      "Assess personal limitations and driving fitness.",
      "Plan continuous improvement after each lesson.",
    ],
  },
];
