"use client";
import { useCallback, useEffect, useState } from "react";
import { createFaq, deleteFaq, getAdminFaqs, updateFaq } from "@/features/API";
import { showToast } from "@/utils/showToast";

const sections = ["home", "general", "instructors", "locations", "driving-code"];
const empty = { question:"",answer:"",question_bn:"",answer_bn:"",question_fr:"",answer_fr:"",section:"home",category:"Driving lessons",order:0,status:"active" };
const languages = [["English","question","answer",true],["বাংলা","question_bn","answer_bn",false],["Français","question_fr","answer_fr",false]];
export default function AdminFaqPage(){
 const [items,setItems]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[filter,setFilter]=useState("all"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const load=useCallback(()=>{setLoading(true);getAdminFaqs(filter==="all"?{}:{section:filter}).then(r=>setItems(r.data?.data||[])).catch(e=>showToast.error(e.response?.data?.message||"FAQs could not be loaded.")).finally(()=>setLoading(false));},[filter]); useEffect(()=>load(),[load]);
 const edit=(x)=>{setEditing(x);setForm({...empty,...x,question_bn:x.translations?.bn?.question||"",answer_bn:x.translations?.bn?.answer||"",question_fr:x.translations?.fr?.question||"",answer_fr:x.translations?.fr?.answer||""});setOpen(true)};
 const close=()=>{setOpen(false);setEditing(null);setForm(empty)};
 const submit=async(e)=>{e.preventDefault();if(!form.question.trim()||!form.answer.trim())return showToast.warning("English question and answer are required.");setSaving(true);try{editing?await updateFaq(editing._id,form):await createFaq(form);showToast.success(`FAQ ${editing?"updated":"created"}.`);close();load()}catch(err){showToast.error(err.response?.data?.message||"FAQ could not be saved.")}finally{setSaving(false)}};
 return <div className="mx-auto max-w-7xl space-y-6"><header className="flex justify-between gap-4"><div><h1 className="text-2xl font-extrabold">FAQ Management</h1><p className="text-sm text-slate-500">Manage English, Bangla and French FAQs.</p></div><button onClick={()=>setOpen(true)} className="rounded-lg bg-[#174a9b] px-5 py-3 font-bold text-white">Create FAQ</button></header><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-lg border px-4 py-3"><option value="all">All sections</option>{sections.map(s=><option key={s}>{s}</option>)}</select><div className="overflow-hidden rounded-xl bg-white shadow"><table className="w-full text-left text-sm"><thead className="bg-[#174a9b] text-white"><tr><th className="p-4">FAQ</th><th>Section</th><th>Status</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{items.map(x=><tr key={x._id} className="border-t"><td className="p-4"><b>{x.question}</b><p className="mt-1 line-clamp-2 text-xs text-slate-500">{x.answer}</p></td><td>{x.section}</td><td>{x.status}</td><td className="p-4 text-right"><button onClick={()=>edit(x)} className="mr-3 font-bold text-blue-700">Edit</button><button onClick={async()=>{if(confirm("Delete this FAQ?")){await deleteFaq(x._id);load()}}} className="font-bold text-red-600">Delete</button></td></tr>)}</tbody></table>{loading&&<p className="p-8 text-center">Loading...</p>}</div>{open&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/50 p-4"><form onSubmit={submit} className="max-h-[92vh] w-full max-w-2xl space-y-5 overflow-y-auto rounded-2xl bg-white p-6"><h2 className="text-xl font-extrabold">{editing?"Update":"Create"} FAQ</h2><div className="grid gap-4 sm:grid-cols-2"><label>Section<select value={form.section} onChange={e=>setForm({...form,section:e.target.value})} className="mt-2 w-full rounded-lg border p-3">{sections.map(s=><option key={s}>{s}</option>)}</select></label><label>Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="mt-2 w-full rounded-lg border p-3"/></label></div>{languages.map(([label,q,a,required])=><section key={q} className="space-y-3 rounded-xl border p-4"><h3 className="font-bold text-[#174a9b]">{label}</h3><input value={form[q]} onChange={e=>setForm({...form,[q]:e.target.value})} placeholder={`Question${required?" *":""}`} className="w-full rounded-lg border p-3"/><textarea rows={4} value={form[a]} onChange={e=>setForm({...form,[a]:e.target.value})} placeholder={`Answer${required?" *":""}`} className="w-full rounded-lg border p-3"/></section>)}<div className="flex justify-end gap-3"><button type="button" onClick={close} className="rounded-lg border px-5 py-3">Cancel</button><button disabled={saving} className="rounded-lg bg-[#e2233d] px-6 py-3 font-bold text-white">{saving?"Saving...":"Save FAQ"}</button></div></form></div>}</div>
}
