"use client";
import Image from "next/image";
import Link from "next/link";
import { FaCarSide, FaStar } from "react-icons/fa";
import useCmsPageContent from "@/hooks/useCmsPageContent";
import { CmsRichText, cmsButtonProps } from "@/components/cms/CmsContent";

const controlClass = "h-[46px] w-full rounded-[10px] border border-[#c9d6e9] bg-[#f6f8fb] px-4 !text-[14px] text-[#1d2734] outline-none transition focus:border-[#174a9b]";
const lines = (value, fallback) => value ? String(value).replace(/<li[^>]*>/gi, "\n").replace(/<br\s*\/?\s*>/gi, "\n").replace(/<[^>]+>/g, "").split("\n").map((x) => x.trim()).filter(Boolean) : fallback;
function Field({ label, type = "text", placeholder }) { return <label className="block"><span className="mb-2 block !text-[14px] font-semibold">{label}</span><input type={type} placeholder={placeholder} className={controlClass} /></label>; }
function SelectField({ label, placeholder, options }) { return <label className="block"><span className="mb-2 block !text-[14px] font-semibold">{label}</span><select defaultValue="" className={`${controlClass} appearance-auto`}><option value="" disabled>{placeholder}</option>{options.map((x) => <option key={x} value={x}>{x}</option>)}</select></label>; }

export default function B2BPartnershipRequestPage() {
  const { content } = useCmsPageContent("b2b-partnership-request");
  const s = content?.settings || {};
  const copy = (key, fallback) => s[key]?.trim?.() || fallback;
  const defaults = ["Exclusive discounts on Driving Licence Packages", "Competitions & prize draws", "Custom landing page with all partnership details", "Ongoing performance tracking and regular updates on results", "Early access to new features and offers"];
  const benefits = defaults.map((x, i) => copy(`benefit${i + 1}`, x));
  const ratings = [1, 2, 3].map((n) => ({ name: copy(`rating${n}Title`, ["VroomVroom", "Google Ratings", "Trustpilot Ratings"][n - 1]), image: s[`rating${n}Image`] }));
  const heroImage = s.heroImage || "/image/request-hero.png";
  return <main className="overflow-hidden bg-[#eef3fb] text-[#202124]">
    <section style={{ backgroundColor: s.heroBackground || "#eaf0f9" }}><div className="mx-auto grid min-h-[560px] max-w-[1350px] items-center gap-12 px-5 py-14 sm:px-8 md:grid-cols-2 lg:px-10"><div><h1 className="text-[34px] font-bold leading-[1.18] sm:text-[40px] lg:text-[42px]">{copy("heroTitle", "Explore partnership opportunities with us")}</h1><CmsRichText html={s.heroDescription} fallback="Benefit from a comprehensive package and exclusive advantages" className="mt-7 !text-[16px] text-[#767a80]" /><Link {...cmsButtonProps(s, "heroButton", { href: "#partnership-form" })} className="mt-10 inline-flex min-h-[48px] min-w-[305px] items-center justify-center rounded-[9px] bg-[#e4213c] px-8 !text-[16px] font-semibold text-white">{copy("heroButton", "Apply for Partnership")}</Link></div><div className="flex justify-center md:justify-end"><Image src={heroImage} alt={copy("heroImageAlt", "Business partnership handshake")} width={700} height={560} priority sizes="(max-width: 768px) 92vw, 560px" className="h-auto w-full max-w-[540px] object-contain" /></div></div></section>
    <section className="bg-white px-5 py-20 sm:px-8 lg:py-24"><div className="mx-auto max-w-[1280px]"><h2 className="text-center text-[34px] font-bold lg:text-[38px]">{copy("sectionTitle", "Are You a Company?")}</h2><CmsRichText html={s.sectionDescription} className="mx-auto mt-4 max-w-3xl text-center !text-[14px] text-[#666b73]" /><div className="mt-12 grid gap-6 lg:grid-cols-[365px_minmax(0,1fr)]"><div className="relative min-h-[500px] overflow-hidden rounded-[12px] bg-[#e8eef8]"><Image src={s.benefitsImage || heroImage} alt={copy("benefitsImageAlt", "Business partnership")} fill sizes="365px" className="object-cover" /></div><div className="flex min-h-[500px] flex-col justify-center rounded-[12px] px-5 py-12 sm:px-12 lg:px-20" style={{ backgroundColor: s.benefitsCardBackground || "#174a9b" }}><h3 className="text-center text-[21px] font-bold text-white">{copy("benefitsTitle", "Exclusive Benefits")}</h3><ul className="mt-8 space-y-5">{benefits.map((x) => <li key={x} className="skew-x-[-11deg] rounded-[9px] bg-[#edf3fb] px-5 py-[14px] text-center"><span className="block skew-x-[11deg] !text-[14px] font-semibold">{x}</span></li>)}</ul></div></div></div></section>
    <section id="partnership-form" className="scroll-mt-24 bg-[#eaf0f9] px-5 py-20 sm:px-8 lg:py-24"><div className="mx-auto max-w-[1060px]"><div className="text-center"><h2 className="text-[34px] font-bold lg:text-[38px]">{copy("formTitle", "Request for Partnership")}</h2><CmsRichText html={s.formDescription} fallback="Fill out this form with necessary information" className="mt-4 !text-[14px] text-[#666b73]" /></div><form className="mt-12 rounded-[12px] bg-white p-5 shadow-sm sm:p-8 lg:p-[30px]" onSubmit={(e) => e.preventDefault()}><h3 className="text-[20px] font-bold">{copy("organizationTitle", "Organization Information")}</h3><div className="mt-6 grid gap-x-7 gap-y-5 md:grid-cols-2">
      <Field label={copy("nameLabel", "Name")} placeholder={copy("namePlaceholder", "Write name here")} /><SelectField label={copy("companyTypeLabel", "Type of company")} placeholder={copy("companyTypePlaceholder", "Select one")} options={lines(s.companyTypeOptions, ["Driving school", "Company", "Association", "Other"])} /><Field label={copy("phoneLabel", "Phone Number")} type="tel" placeholder={copy("phonePlaceholder", "Write phone number")} /><Field label={copy("emailLabel", "Email Address")} type="email" placeholder={copy("emailPlaceholder", "Write email address")} /><Field label={copy("cityLabel", "City")} placeholder={copy("cityPlaceholder", "Write city")} /><Field label={copy("addressLabel", "Address")} placeholder={copy("addressPlaceholder", "Write address")} />
      <label className="block md:col-span-2"><span className="block !text-[14px] font-semibold">{copy("expectationLabel", "What do you expect from this partnership?")}</span><span className="mb-2 block !text-[13px] text-[#6d7279]">{copy("expectationHelp", "Please specify the objectives of this partnership so we can learn more!")}</span><textarea rows={7} placeholder={copy("messagePlaceholder", "Write message")} className="w-full resize-none rounded-[10px] border border-[#c9d6e9] bg-[#f6f8fb] p-4 !text-[14px] outline-none" /></label>
      <SelectField label={copy("beneficiariesLabel", "Approximate number of beneficiaries of the partnership*")} placeholder={copy("beneficiariesPlaceholder", "Select one")} options={lines(s.beneficiariesOptions, ["1-20", "21-50", "51-100", "More than 100"])} /><SelectField label={copy("referralLabel", "How did you hear about us?")} placeholder={copy("referralPlaceholder", "Select one")} options={lines(s.referralOptions, ["Google", "Social media", "Recommendation", "Other"])} />
    </div><button type="submit" className="mt-6 rounded-[8px] px-7 py-3 !text-[15px] font-semibold" style={{ backgroundColor: s.submitButtonColor || "#e4213c", color: s.submitButtonTextColor || "#fff" }}>{copy("submitButton", "Submit")}</button></form></div></section>
    <section className="px-5 py-16 sm:px-8 lg:py-20" style={{ backgroundColor: s.ratingsBackground || "#174a9b" }}><div className="mx-auto grid max-w-[1280px] gap-6 md:grid-cols-3">{ratings.map((r, i) => <article key={r.name} className="flex min-h-[168px] flex-col items-center justify-center rounded-[22px] bg-[#f6f8fb] px-6 py-6 text-center">{r.image ? <Image src={r.image} alt="" width={40} height={40} className="h-10 w-10 object-contain" /> : <span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#1367ba] text-white"><FaCarSide /></span>}<h3 className="mt-2 text-[19px] font-bold">{r.name}</h3><div className="mt-1 flex gap-2 text-[#ffc52c]" aria-label={copy("ratingAriaLabel", "Five stars")}>{[0,1,2,3,4].map((x) => <FaStar key={`${i}-${x}`} className="text-[18px]" />)}</div><p className="mt-1 !text-[14px]">{copy("ratingScore", "04 out of 05")}</p></article>)}</div></section>
  </main>;
}
