"use client";

import { useEffect, useState } from "react";
import { createLearningContent, getAdminLearningContents, permanentlyDeleteLearningContent, updateLearningContent } from "@/features/API";
import { mediaUrl } from "@/utils/mediaUrl";

const empty={title:"",description:"",readMinutes:3,status:"active",order:0}; const PAGE_SIZE=10;
export default function AdminKnowledgeSheetsPage(){const[allItems,setItems]=useState([]);const[page,setPage]=useState(0);const[form,setForm]=useState(empty);const[file,setFile]=useState(null);const[editing,setEditing]=useState(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[notice,setNotice]=useState("");
  const load=()=>getAdminLearningContents({type:"knowledge-sheet"}).then(({data})=>setItems(data?.data||[])).catch((e)=>setNotice(e.response?.data?.message||"Could not load sheets.")).finally(()=>setLoading(false));useEffect(()=>{load();},[]);
  const reset=()=>{setForm(empty);setFile(null);setEditing(null);};
  const submit=async(e)=>{e.preventDefault();if(!form.title.trim()||(!editing&&!file))return setNotice("Title and PDF are required.");const data=new FormData();data.append("type","knowledge-sheet");Object.entries(form).forEach(([key,value])=>data.append(key,value));if(file)data.append("file",file);setSaving(true);try{editing?await updateLearningContent(editing,data):await createLearningContent(data);setNotice(editing?"Knowledge sheet updated.":"Knowledge sheet created.");reset();await load();}catch(err){setNotice(err.response?.data?.message||"Could not save sheet.");}finally{setSaving(false);}};
  const edit=(item)=>{setEditing(item._id);setForm({title:item.title||"",description:item.description||"",readMinutes:item.readMinutes||0,status:item.status||"active",order:item.order||0});setFile(null);window.scrollTo({top:0,behavior:"smooth"});};
  const remove=async(item)=>{if(!confirm(`Permanently delete "${item.title}"?`))return;await permanentlyDeleteLearningContent(item._id);if(editing===item._id)reset();await load();};
  const pages=Math.max(1,Math.ceil(allItems.length/PAGE_SIZE));const items=allItems.slice(page*PAGE_SIZE,page*PAGE_SIZE+PAGE_SIZE);
  return <main className="min-h-screen bg-[#f5f7fb] p-4 sm:p-6"><div className="mx-auto max-w-7xl"><h1 className="text-2xl font-bold text-[#173f87]">Knowledge Sheets</h1><p className="mt-1 text-sm text-slate-500">Upload and manage downloadable PDF revision sheets.</p><form onSubmit={submit} className="mt-6 rounded-2xl bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Field label="Title *" value={form.title} onChange={(value)=>setForm({...form,title:value})}/><Field label="Mini description" value={form.description} onChange={(value)=>setForm({...form,description:value})}/><Field type="number" label="Read time (minutes)" value={form.readMinutes} onChange={(value)=>setForm({...form,readMinutes:value})}/><Field type="number" label="Display order" value={form.order} onChange={(value)=>setForm({...form,order:value})}/><label className="text-xs font-bold">PDF file {editing?"":"*"}<input type="file" accept="application/pdf,.pdf" onChange={(e)=>setFile(e.target.files?.[0]||null)} className="mt-2 block w-full font-normal"/></label></div><div className="mt-4 flex flex-wrap items-center gap-3"><select value={form.status} onChange={(e)=>setForm({...form,status:e.target.value})} className="rounded-lg border px-3 py-2"><option value="active">Active</option><option value="inactive">Inactive</option><option value="draft">Draft</option></select><button disabled={saving} className="rounded-lg bg-[#173f87] px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving?"Saving...":editing?"Update Sheet":"Add Sheet"}</button>{editing&&<button type="button" onClick={reset} className="rounded-lg bg-slate-100 px-5 py-2.5 text-sm font-bold">Cancel</button>}{notice&&<span className="text-sm font-semibold text-slate-600">{notice}</span>}</div></form>
    <section className="mt-6 rounded-2xl bg-[#e8eef7] p-4">{loading?<p>Loading...</p>:<div className="grid gap-3 md:grid-cols-2">{items.map((item)=><article key={item._id} className="rounded-xl bg-white p-4"><div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><h2 className="break-words font-bold">{item.title}</h2><p className="mt-1 line-clamp-2 text-xs text-slate-500">{item.description}</p><p className="mt-2 text-xs font-semibold text-[#173f87]">{item.readMinutes||0} min · {item.status}</p></div>{item.fileUrl&&<a href={mediaUrl(item.fileUrl)} target="_blank" className="shrink-0 text-xs font-bold text-blue-700">PDF</a>}</div><div className="mt-3 flex gap-2"><button onClick={()=>edit(item)} className="rounded bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700">Edit</button><button onClick={()=>remove(item)} className="rounded bg-red-50 px-3 py-1.5 text-xs font-bold text-red-700">Delete</button></div></article>)}</div>}</section><div className="mt-4 flex items-center justify-between rounded-xl bg-white px-4 py-3"><p className="text-xs text-slate-500">Page {page+1} of {pages} · {allItems.length} sheets</p><div className="flex gap-2"><button disabled={page===0} onClick={()=>setPage((value)=>value-1)} className="rounded-lg border px-4 py-2 text-xs font-bold disabled:opacity-40">Previous</button><button disabled={page+1>=pages} onClick={()=>setPage((value)=>value+1)} className="rounded-lg bg-[#173f87] px-4 py-2 text-xs font-bold text-white disabled:opacity-40">Next</button></div></div></div></main>;
}
function Field({label,value,onChange,type="text"}){return <label className="text-xs font-bold">{label}<input type={type} min={type==="number"?0:undefined} value={value} onChange={(e)=>onChange(e.target.value)} className="mt-2 w-full rounded-lg border px-3 py-2.5 font-normal"/></label>}
