"use client";
import { use, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { IoChevronBack } from "react-icons/io5";
import { getLearningContentById, updateLearningProgress } from "@/features/API";
import { mediaUrl } from "@/utils/mediaUrl";

export default function LessonPage({params}){const{id}=use(params);const router=useRouter();const[lesson,setLesson]=useState(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");useEffect(()=>{getLearningContentById(id).then(({data})=>{setLesson(data?.data);updateLearningProgress(id,{status:"in_progress",readPercent:10}).catch(()=>{});}).catch((e)=>setError(e.response?.data?.message||"Lesson could not be loaded.")).finally(()=>setLoading(false));},[id]);if(loading)return <div className="min-h-screen animate-pulse bg-white p-8"><div className="mx-auto h-[600px] max-w-4xl rounded-2xl bg-[#e8eef7]"/></div>;
return <main className="min-h-screen bg-white px-3 py-6 sm:px-6"><div className="mx-auto max-w-[900px]"><header className="flex items-center gap-4"><button onClick={()=>router.back()} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#e8edf5]"><IoChevronBack size={25}/></button><h1 className="break-words text-xl font-semibold text-[#173f87] sm:text-2xl">{lesson?.title||"Lesson"}</h1></header>{error?<p className="mt-8 rounded-xl bg-red-50 p-5 text-red-700">{error}</p>:lesson&&<article className="mt-8 rounded-2xl bg-[#e8eef7] p-4 sm:p-6"><img src={mediaUrl(lesson.image)} alt={lesson.title} className="max-h-[430px] w-full rounded-xl bg-white object-cover"/><div className="ebook-content mt-5 break-words rounded-xl bg-white p-5 leading-7 text-slate-700 sm:p-8" dangerouslySetInnerHTML={{__html:lesson.content||"<p>No lesson content available.</p>"}}/><button onClick={()=>updateLearningProgress(id,{status:"completed",readPercent:100}).then(()=>router.back())} className="mt-6 rounded-lg bg-[#e3263c] px-6 py-3 text-sm font-bold text-white">Mark as completed</button></article>}<style jsx global>{`.ebook-content h2{margin:1.5rem 0 .65rem;font-size:1.35rem;font-weight:800;color:#173f87}.ebook-content h3{margin:1.2rem 0 .5rem;font-size:1.1rem;font-weight:800;color:#173f87}.ebook-content p{margin:.75rem 0}.ebook-content ul,.ebook-content ol{margin:.75rem 0;padding-left:1.5rem}.ebook-content ul{list-style:disc}.ebook-content ol{list-style:decimal}.ebook-content a{color:#174a9b;text-decoration:underline}.ebook-content figure{margin:1.5rem auto}.ebook-content img{max-width:100%;height:auto;border-radius:.75rem}`}</style></div></main>}
