"use client";

import { useCallback, useEffect, useState } from "react";
import { createExamQuestion, deleteExamQuestion, getAdminExamQuestions, updateExamQuestion } from "@/features/API";
import { mediaUrl } from "@/utils/mediaUrl";

const emptyForm = () => ({ number: "", title: "", category: "General", videoUrl: "", order: 0, status: "active", items: [{ question: "", answer: "" }] });

export default function AdminExamQuestionsPage() {
  const [items, setItems] = useState([]); const [meta, setMeta] = useState({ page: 1, totalPages: 1, total: 0 });
  const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState(""); const [image, setImage] = useState(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [search, setSearch] = useState("");
  const load = useCallback(async (page = 1) => { setLoading(true); try { const response = await getAdminExamQuestions({ page, limit: 10, search }); setItems(response.data?.data || []); setMeta(response.data?.meta || { page, totalPages: 1, total: 0 }); } catch (error) { setMessage(error.response?.data?.message || "Questions could not be loaded."); } finally { setLoading(false); } }, [search]);
  useEffect(() => { load(1); }, [load]);
  const reset = () => { setForm(emptyForm()); setEditing(""); setImage(null); };
  const changePair = (index, field, value) => setForm((current) => ({ ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item) }));
  const submit = async (event) => { event.preventDefault(); setMessage(""); if (!form.number || form.items.some((item) => !item.question.trim() || !item.answer.trim())) return setMessage("Number and every question-answer pair are required."); const data = new FormData(); ["number", "title", "category", "videoUrl", "order", "status"].forEach((key) => data.append(key, form[key])); data.append("items", JSON.stringify(form.items)); if (image) data.append("image", image); setSaving(true); try { editing ? await updateExamQuestion(editing, data) : await createExamQuestion(data); setMessage(editing ? "Question updated." : "Question created."); reset(); await load(meta.page); } catch (error) { setMessage(error.response?.data?.message || "Question could not be saved."); } finally { setSaving(false); } };
  const edit = (item) => { setEditing(item._id); setForm({ number: item.number, title: item.title || "", category: item.category || "General", videoUrl: item.videoUrl || "", order: item.order || 0, status: item.status || "active", items: item.items?.map(({ question, answer }) => ({ question, answer })) || [{ question: "", answer: "" }] }); setImage(null); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const remove = async (id) => { if (!window.confirm("Delete this exam question?")) return; try { await deleteExamQuestion(id); await load(meta.page); } catch (error) { setMessage(error.response?.data?.message || "Question could not be deleted."); } };
  return <main className="min-h-screen bg-[#f5f7fb] p-4 sm:p-6"><div className="mx-auto max-w-7xl"><h1 className="text-2xl font-bold text-[#173f87]">Exam Questions</h1><p className="mt-1 text-sm text-slate-500">Manage the read-only questions shown in the student driving exam guide.</p>
    <form onSubmit={submit} className="mt-6 rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold text-[#173f87]">{editing ? "Edit Question" : "Add Question"}</h2>{editing && <button type="button" onClick={reset} className="text-sm font-bold text-slate-500">Cancel edit</button>}</div><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Field label="Number *"><input type="number" min="1" max="999" value={form.number} onChange={(e) => setForm({ ...form, number: e.target.value })} className="input" /></Field><Field label="Title"><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className="input" /></Field><Field label="Category"><input value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} className="input" /></Field><Field label="Order"><input type="number" value={form.order} onChange={(e) => setForm({ ...form, order: e.target.value })} className="input" /></Field><Field label="Image"><input type="file" accept="image/*" onChange={(e) => setImage(e.target.files?.[0] || null)} className="mt-2 block w-full text-xs" /></Field><Field label="Video explanation URL"><input type="url" value={form.videoUrl} onChange={(e) => setForm({ ...form, videoUrl: e.target.value })} className="input" /></Field><Field label="Status"><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })} className="input"><option value="active">Active</option><option value="inactive">Inactive</option></select></Field></div>
    <div className="mt-5 space-y-3"><div className="flex items-center justify-between"><h3 className="text-sm font-bold text-[#173f87]">Question & answer pairs</h3><button type="button" onClick={() => setForm({ ...form, items: [...form.items, { question: "", answer: "" }] })} className="rounded-lg bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">+ Add pair</button></div>{form.items.map((pair, index) => <div key={index} className="grid gap-3 rounded-xl bg-[#e8eef7] p-3 md:grid-cols-2"><textarea value={pair.question} onChange={(e) => changePair(index, "question", e.target.value)} placeholder={`Question ${index + 1}`} rows="3" className="rounded-lg border border-slate-200 p-3 text-sm" /><div className="flex gap-2"><textarea value={pair.answer} onChange={(e) => changePair(index, "answer", e.target.value)} placeholder="Correct explanation / answer" rows="3" className="min-w-0 flex-1 rounded-lg border border-slate-200 p-3 text-sm" />{form.items.length > 1 && <button type="button" onClick={() => setForm({ ...form, items: form.items.filter((_, i) => i !== index) })} className="self-start rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-700">Remove</button>}</div></div>)}</div><div className="mt-5 flex items-center gap-3"><button disabled={saving} className="rounded-lg bg-[#173f87] px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving ? "Saving..." : editing ? "Update Question" : "Create Question"}</button>{message && <p className="text-sm font-semibold text-slate-600">{message}</p>}</div></form>
    <section className="mt-6 rounded-2xl bg-[#e8eef7] p-4"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><b className="text-[#173f87]">{meta.total || 0} questions</b><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search title or category" className="rounded-lg border px-3 py-2 text-sm" /></div>{loading ? <div className="h-48 animate-pulse rounded-xl bg-white" /> : <div className="overflow-x-auto rounded-xl bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#173f87] text-white"><tr><th className="p-3">No.</th><th className="p-3">Media</th><th className="p-3">Title / Category</th><th className="p-3">Pairs</th><th className="p-3">Status</th><th className="p-3 text-right">Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item._id} className="border-b"><td className="p-3 font-bold">{String(item.number).padStart(2, "0")}</td><td className="p-3">{item.image ? <img src={mediaUrl(item.image)} alt="" className="h-12 w-20 rounded object-cover" /> : "—"}</td><td className="p-3"><b>{item.title || `Question ${item.number}`}</b><p className="text-xs text-slate-500">{item.category}</p></td><td className="p-3">{item.items?.length || 0}</td><td className="p-3 capitalize">{item.status}</td><td className="p-3 text-right"><button onClick={() => edit(item)} className="mr-2 rounded bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700">Edit</button><button onClick={() => remove(item._id)} className="rounded bg-red-50 px-3 py-1.5 text-xs font-bold text-red-700">Delete</button></td></tr>)}</tbody></table>{!items.length && <p className="p-10 text-center text-slate-500">No questions added yet.</p>}</div>}<div className="mt-4 flex justify-end gap-2"><button disabled={meta.page <= 1} onClick={() => load(meta.page - 1)} className="rounded-lg bg-white px-4 py-2 text-xs font-bold disabled:opacity-40">Previous</button><span className="rounded-lg bg-white px-4 py-2 text-xs">Page {meta.page || 1} / {meta.totalPages || 1}</span><button disabled={meta.page >= meta.totalPages} onClick={() => load(meta.page + 1)} className="rounded-lg bg-white px-4 py-2 text-xs font-bold disabled:opacity-40">Next</button></div></section>
    <style jsx>{`.input{margin-top:.5rem;width:100%;border:1px solid #e2e8f0;border-radius:.5rem;padding:.625rem .75rem;font-weight:400}`}</style></div></main>;
}
function Field({ label, children }) { return <label className="text-sm font-semibold text-slate-700">{label}{children}</label>; }
