"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { deleteExamQuestion, getAdminExamQuestions } from "@/features/API";
import { mediaUrl } from "@/utils/mediaUrl";

export default function ExamQuestionsListPage() {
  const [items, setItems] = useState([]); const [meta, setMeta] = useState({ page: 1, totalPages: 1, total: 0 }); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  const load = useCallback(async (page = 1) => { setLoading(true); try { const response = await getAdminExamQuestions({ page, limit: 10, search }); setItems(response.data?.data || []); setMeta(response.data?.meta || { page, totalPages: 1, total: 0 }); } catch (error) { setMessage(error.response?.data?.message || "Questions could not be loaded."); } finally { setLoading(false); } }, [search]);
  useEffect(() => { const timer = setTimeout(() => load(1), 300); return () => clearTimeout(timer); }, [load]);
  const remove = async (item) => { if (!window.confirm(`Delete question ${item.number}?`)) return; try { await deleteExamQuestion(item._id); await load(meta.page); } catch (error) { setMessage(error.response?.data?.message || "Question could not be deleted."); } };
  return <main className="min-h-screen bg-[#f5f7fb] p-4 sm:p-6"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-[#173f87]">Exam Questions</h1><p className="mt-1 text-sm text-slate-500">Manage student driving exam guide questions.</p></div><Link href="/admin/exam-questions/create" className="rounded-lg bg-[#df2339] px-5 py-2.5 text-sm font-bold text-white">+ Create Question</Link></div>
    <section className="mt-6 rounded-2xl bg-[#e8eef7] p-4"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><b className="text-[#173f87]">{meta.total} questions</b><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search title or category" className="w-full rounded-lg border bg-white px-4 py-2.5 text-sm sm:w-72" /></div>{message && <p className="mb-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{message}</p>}{loading ? <div className="h-64 animate-pulse rounded-xl bg-white" /> : <div className="overflow-x-auto rounded-xl bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#173f87] text-white"><tr><th className="p-3">No.</th><th className="p-3">Media</th><th className="p-3">Title</th><th className="p-3">Category</th><th className="p-3">Pairs</th><th className="p-3">Status</th><th className="p-3 text-right">Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item._id} className="border-b hover:bg-slate-50"><td className="p-3 font-bold">{String(item.number).padStart(2, "0")}</td><td className="p-3">{item.videoUrl ? <span className="rounded-full bg-purple-100 px-3 py-1 text-xs font-bold text-purple-700">Video</span> : item.image ? <img src={mediaUrl(item.image)} alt="" className="h-12 w-20 rounded object-cover" /> : "—"}</td><td className="p-3 font-semibold">{item.title || `Question ${item.number}`}</td><td className="p-3 text-slate-600">{item.category}</td><td className="p-3">{item.items?.length || 0}</td><td className="p-3"><span className={`rounded-full px-3 py-1 text-xs font-bold ${item.status === "active" ? "bg-green-100 text-green-700" : "bg-slate-100 text-slate-600"}`}>{item.status}</span></td><td className="p-3 text-right"><Link href={`/admin/exam-questions/${item._id}/edit`} className="mr-2 rounded bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">Edit</Link><button onClick={() => remove(item)} className="rounded bg-red-50 px-3 py-2 text-xs font-bold text-red-700">Delete</button></td></tr>)}</tbody></table>{!items.length && <p className="p-12 text-center text-slate-500">No questions found.</p>}</div>}<div className="mt-4 flex items-center justify-between"><span className="text-xs text-slate-500">Page {meta.page} of {meta.totalPages}</span><div className="flex gap-2"><button disabled={meta.page <= 1} onClick={() => load(meta.page - 1)} className="rounded-lg bg-white px-4 py-2 text-xs font-bold disabled:opacity-40">Previous</button><button disabled={meta.page >= meta.totalPages} onClick={() => load(meta.page + 1)} className="rounded-lg bg-[#173f87] px-4 py-2 text-xs font-bold text-white disabled:opacity-40">Next</button></div></div></section>
  </div></main>;
}
